/* ALVR is licensed under the MIT license. https://github.com/alvr-org/ALVR/blob/master/LICENSE */

#ifndef ALVR_RUNTIME_BRIDGE_H
#define ALVR_RUNTIME_BRIDGE_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Regenerate via `ALVR_REGENERATE_BRIDGE_HEADER=1 cargo build -p alvr_server_openxr`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Bridge ABI version. Bump this **and** the matching expectation in the
 * Monado-side ALVR driver (`openxr/src/xrt/drivers/alvr/alvr_hub.c`'s
 * `ALVR_OXR_BRIDGE_ABI_EXPECTED`) on every incompatible change to the
 * surface defined below — added/removed/reordered exports, changed struct
 * layouts, changed enum discriminants, changed argument lists, semantic
 * changes to existing calls.
 *
 * Initial value `1`. Increment monotonically; do not reuse old values.
 *
 * At driver init the Monado side calls [`alvr_oxr_get_bridge_abi_version`]
 * and compares against the macro cbindgen emits for this const. A mismatch
 * means the loaded `alvr_server_openxr` cdylib was built against a
 * different bridge surface than the driver's compiled header expected
 * (typically: somebody rebuilt one half without bumping the submodule
 * pointer for the other half).
 *
 * History:
 * - v1: initial surface (Phase 3.1 / 3.2).
 * - v2: added [`alvr_oxr_report_pacing`] so the Monado-side compositor can
 *   forward per-frame `u_pc_*` timing data into `alvr_server_core`'s
 *   metrics exporter (Phase 5 telemetry bridge).
 * - v3: added [`alvr_oxr_report_layer_types`] so the compositor can report
 *   per-frame counts of submitted non-projection layer types (quad /
 *   cylinder / equirect / cube / passthrough) that the runtime currently
 *   drops (Phase 7 Slice 1; diagnostic before quad rasterisation lands).
 */
#define ALVR_OXR_BRIDGE_ABI_VERSION 3

#define ALVR_OXR_BUTTON_A_CLICK (1 << 0)

#define ALVR_OXR_BUTTON_A_TOUCH (1 << 1)

#define ALVR_OXR_BUTTON_B_CLICK (1 << 2)

#define ALVR_OXR_BUTTON_B_TOUCH (1 << 3)

#define ALVR_OXR_BUTTON_X_CLICK (1 << 4)

#define ALVR_OXR_BUTTON_X_TOUCH (1 << 5)

#define ALVR_OXR_BUTTON_Y_CLICK (1 << 6)

#define ALVR_OXR_BUTTON_Y_TOUCH (1 << 7)

#define ALVR_OXR_BUTTON_MENU_CLICK (1 << 8)

#define ALVR_OXR_BUTTON_SYSTEM_CLICK (1 << 9)

#define ALVR_OXR_BUTTON_THUMBSTICK_CLICK (1 << 10)

#define ALVR_OXR_BUTTON_THUMBSTICK_TOUCH (1 << 11)

#define ALVR_OXR_BUTTON_TRIGGER_CLICK (1 << 12)

#define ALVR_OXR_BUTTON_TRIGGER_TOUCH (1 << 13)

#define ALVR_OXR_BUTTON_SQUEEZE_CLICK (1 << 14)

#define ALVR_OXR_BUTTON_THUMBREST_TOUCH (1 << 15)

#define ALVR_OXR_DEVICE_KIND_OTHER 0

#define ALVR_OXR_DEVICE_KIND_HMD 1

#define ALVR_OXR_DEVICE_KIND_LEFT_CONTROLLER 2

#define ALVR_OXR_DEVICE_KIND_RIGHT_CONTROLLER 3

/**
 * Resolution of the basis-points gauge encoding in [`encode_battery`]:
 * `gauge_value ∈ [0.0, 1.0]` becomes `0..=ALVR_OXR_BATTERY_GAUGE_SCALE`.
 * 10000 gives 0.01% resolution, plenty for a battery percent indicator.
 */
#define ALVR_OXR_BATTERY_GAUGE_SCALE 10000

/**
 * Result codes returned across the FFI boundary. Mirrors `xrt_result_t`
 * loosely but is intentionally a separate enum so that the bridge ABI can
 * evolve independently of Monado.
 */
enum AlvrOxrResult
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * Operation succeeded.
   */
  ALVR_OXR_RESULT_OK = 0,
  /**
   * Operation is not yet implemented in this build of ALVR.
   */
  ALVR_OXR_RESULT_NOT_IMPLEMENTED = -1,
  /**
   * Operation failed for an unspecified reason.
   */
  ALVR_OXR_RESULT_FAILED = -2,
  /**
   * The OpenXR mode has not been initialised yet.
   */
  ALVR_OXR_RESULT_NOT_INITIALISED = -3,
};
#ifndef __cplusplus
typedef int32_t AlvrOxrResult;
#endif // __cplusplus

/**
 * Per-side identifier for hand/controller bridge calls.
 */
enum AlvrOxrSide
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
  ALVR_OXR_SIDE_LEFT = 0,
  ALVR_OXR_SIDE_RIGHT = 1,
};
#ifndef __cplusplus
typedef uint8_t AlvrOxrSide;
#endif // __cplusplus

/**
 * Session-event type discriminant. Mirrors `enum xrt_session_event_type`
 * loosely; trimmed down to what ALVR cares about.
 */
enum AlvrOxrEventType
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  ALVR_OXR_EVENT_TYPE_NONE = 0,
  ALVR_OXR_EVENT_TYPE_STATE_CHANGE = 1,
  ALVR_OXR_EVENT_TYPE_BATTERY = 2,
  ALVR_OXR_EVENT_TYPE_CONNECTION_LOST = 4,
  ALVR_OXR_EVENT_TYPE_REFRESH_RATE_CHANGE = 5,
};
#ifndef __cplusplus
typedef int32_t AlvrOxrEventType;
#endif // __cplusplus

/**
 * Pose returned by the bridge. Coordinate convention follows OpenXR
 * (right-handed, +Y up, -Z forward).
 */
typedef struct AlvrOxrPose {
  float position[3];
  float orientation[4];
} AlvrOxrPose;

/**
 * Per-view static parameters: the eye-to-head pose offset and the
 * per-view field of view, both in OpenXR conventions (radians for FOV,
 * right-handed +Y up -Z forward for the pose). `fov_radians` is
 * `[left, right, up, down]` to match [`AlvrOxrLayer::fov_radians`].
 *
 * These come from the client's reported view configuration and arrive
 * on `ServerCoreEvent::LocalViewParams`. The bridge caches them in a
 * global so [`alvr_oxr_get_view_params`] can return them synchronously
 * — Monado's `xrLocateViews` equivalent calls into us once per frame
 * and shouldn't block on the connection thread.
 */
typedef struct AlvrOxrViewParams {
  struct AlvrOxrPose pose;
  float fov_radians[4];
} AlvrOxrViewParams;

/**
 * Per-frame controller state passed back over the bridge. Buttons and
 * analogue values mirror the OpenXR Touch profile layout.
 */
typedef struct AlvrOxrControllerState {
  struct AlvrOxrPose pose;
  float linear_velocity[3];
  float angular_velocity[3];
  float trigger;
  float squeeze;
  float thumbstick[2];
  uint32_t buttons;
} AlvrOxrControllerState;

/**
 * Haptic pulse parameters. Maps onto OpenXR `XrHapticVibration`.
 */
typedef struct AlvrOxrHaptic {
  int64_t duration_ns;
  float frequency_hz;
  float amplitude;
} AlvrOxrHaptic;

/**
 * One submitted OpenXR composition layer. The Monado-side compositor builds
 * an array of these and hands them to the bridge once per frame.
 *
 * Image handles are platform-specific:
 * * Windows: `HANDLE` from a `D3D11_RESOURCE_MISC_SHARED_NTHANDLE` resource
 *   or `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32` (`u64` of the HANDLE).
 * * Linux: DMABUF fd (cast to `u64`).
 */
typedef struct AlvrOxrLayer {
  uint32_t layer_type;
  uint32_t view_count;
  uint64_t image_handles[2];
  uint32_t width;
  uint32_t height;
  float fov_radians[4];
  struct AlvrOxrPose pose;
} AlvrOxrLayer;

typedef struct AlvrOxrEvent {
  AlvrOxrEventType event_type;
  int64_t timestamp_ns;
  int32_t data[4];
} AlvrOxrEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the bridge ABI version baked into this cdylib at compile time.
 * See [`ALVR_OXR_BRIDGE_ABI_VERSION`].
 *
 * # Safety
 * Always safe to call; no preconditions, no shared state touched.
 */
uint32_t alvr_oxr_get_bridge_abi_version(void);

/**
 * Initialise the OpenXR-mode bridge. Called once by the Monado-side ALVR
 * driver at process start (after Monado has loaded `libalvr_server_openxr`).
 *
 * `root_dir` is the parent directory ALVR uses for `session.json`, log
 * output, and the embedded web server's working dir — the OpenXR-mode
 * analogue of the OpenVR driver root. The Monado-side driver typically
 * derives this from an env var (`ALVR_ROOT`) or from the path of the
 * loaded cdylib.
 *
 * # Safety
 * `root_dir` must be a valid NUL-terminated UTF-8 C string. The bridge
 * must be called from a single thread before any other bridge function.
 */
AlvrOxrResult alvr_oxr_init(const char *root_dir);

/**
 * Shut down the OpenXR-mode bridge. Called once by the Monado-side ALVR
 * driver at process exit.
 *
 * # Safety
 * Must be called after the last bridge call has returned.
 */
void alvr_oxr_shutdown(void);

/**
 * Fill `out_serial` with the HMD's serial string. `buf_len` is the caller's
 * buffer size; the bridge writes at most `buf_len - 1` bytes plus a NUL.
 *
 * # Safety
 * `out_serial` must be a writable buffer of at least `buf_len` bytes, and
 * `buf_len >= 1`.
 */
AlvrOxrResult alvr_oxr_get_hmd_info(char *out_serial, uintptr_t buf_len);

/**
 * Fill `out_serial` with the controller's serial string. See
 * [`alvr_oxr_get_hmd_info`] for the buffer contract.
 *
 * # Safety
 * `out_serial` must be a writable buffer of at least `buf_len` bytes, and
 * `buf_len >= 1`.
 */
AlvrOxrResult alvr_oxr_get_controller_info(AlvrOxrSide side, char *out_serial, uintptr_t buf_len);

/**
 * Query the predicted head pose at `at_timestamp_ns` (CLOCK_MONOTONIC ns).
 *
 * # Safety
 * `out_pose` must be a writable `AlvrOxrPose`.
 */
AlvrOxrResult alvr_oxr_get_head_pose(int64_t at_timestamp_ns, struct AlvrOxrPose *out_pose);

/**
 * Read the cached view parameters for `side` (Left = view 0, Right = view 1).
 * Returns Ok with the latest cached params; before the client has reported
 * its view configuration the returned values reflect `ViewParams::DUMMY`
 * (identity pose + ±1 rad fov) so Monado doesn't trip on uninitialised
 * memory.
 *
 * # Safety
 * `out_params` must be a writable `AlvrOxrViewParams`.
 */
AlvrOxrResult alvr_oxr_get_view_params(AlvrOxrSide side, struct AlvrOxrViewParams *out_params);

/**
 * Query the controller state at `at_timestamp_ns`.
 *
 * # Safety
 * `out_state` must be a writable `AlvrOxrControllerState`.
 */
AlvrOxrResult alvr_oxr_get_controller_state(AlvrOxrSide side,
                                            int64_t at_timestamp_ns,
                                            struct AlvrOxrControllerState *out_state);

/**
 * Trigger a haptic pulse on the given controller.
 *
 * # Safety
 * `params` must point to a valid `AlvrOxrHaptic`.
 */
AlvrOxrResult alvr_oxr_set_haptic(AlvrOxrSide side, const struct AlvrOxrHaptic *params);

/**
 * Submit a frame's worth of composition layers.
 *
 * # Safety
 * `layers` must point to `layer_count` valid `AlvrOxrLayer`s. `sync_handle`
 * may be 0 to indicate "no GPU sync, use a fence".
 */
AlvrOxrResult alvr_oxr_submit_layers(int64_t frame_id,
                                     uint32_t layer_count,
                                     const struct AlvrOxrLayer *layers,
                                     uint64_t sync_handle);

/**
 * Report per-frame compositor pacing timestamps for telemetry.
 *
 * Called by the Monado-side `comp_alvr` after the `layer_commit` pacing
 * markers fire (matches `u_pc_mark_point` semantics):
 * - `begin_ns` — start of compositor work for this frame
 *   (`U_TIMING_POINT_BEGIN`).
 * - `submit_begin_ns` — moment work is handed to the GPU/encoder, i.e.
 *   just before [`alvr_oxr_submit_layers`] (`U_TIMING_POINT_SUBMIT_BEGIN`).
 * - `submit_end_ns` — moment the handoff completed
 *   (`U_TIMING_POINT_SUBMIT_END`).
 *
 * All timestamps are in nanoseconds from the same monotonic clock used by
 * `u_pacing` (`os_monotonic_get_ns()`). The bridge intentionally accepts
 * raw timestamps rather than pre-computed deltas so the Rust side can build
 * any window/aggregation shape it likes.
 *
 * Forwards the sample into `alvr_server_core`'s metrics exporter via
 * [`ServerCoreContext::report_oxr_pacing`]. The metrics aggregator
 * derives CPU and submit durations and exports them in the standard
 * per-window snapshot under the `oxr_pacing` field. Drops silently when
 * no client is connected (no metrics sender wired up yet) or when the
 * bridge context is not initialised. Always returns `Ok` so the
 * compositor doesn't log a per-frame failure.
 *
 * # Safety
 * Always safe to call. Takes only `Copy` POD values.
 */
AlvrOxrResult alvr_oxr_report_pacing(int64_t frame_id,
                                     int64_t begin_ns,
                                     int64_t submit_begin_ns,
                                     int64_t submit_end_ns);

/**
 * Report per-frame counts of non-projection layers the compositor saw.
 *
 * `comp_alvr` currently passes only `XRT_LAYER_PROJECTION` /
 * `XRT_LAYER_PROJECTION_DEPTH` layers to the encoder and drops everything
 * else. This entrypoint lets it report what was dropped so the metrics
 * exporter can surface "what kinds of overlays do real apps actually
 * submit" — a useful prior for Phase 7 rasterisation work (build quad
 * support first if most apps submit quads, etc.).
 *
 * Each `n_*` count is the number of layers of that type on this single
 * frame. Frame-id is taken purely so future versions can correlate with
 * the pacing sample for the same frame; the current aggregator does not
 * retain it.
 *
 * Always returns `Ok`. Drops silently when no client is connected.
 *
 * # Safety
 * Always safe to call. Takes only `Copy` POD values.
 */
AlvrOxrResult alvr_oxr_report_layer_types(int64_t frame_id,
                                          uint32_t n_quad,
                                          uint32_t n_cylinder,
                                          uint32_t n_equirect,
                                          uint32_t n_cube,
                                          uint32_t n_passthrough);

/**
 * Poll one session event from the bridge. Returns
 * [`AlvrOxrResult::Ok`] with `out_event.event_type == None` when the queue
 * is empty.
 *
 * # Safety
 * `out_event` must be a writable `AlvrOxrEvent`.
 */
AlvrOxrResult alvr_oxr_poll_session_event(struct AlvrOxrEvent *out_event);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ALVR_RUNTIME_BRIDGE_H */
