//! OpenXR (Monado) integration for the PC side of ALVR.
//!
//! This crate is the OpenXR analogue of `alvr_server_openvr`. It exports the
//! C ABI defined in `include/alvr_runtime_bridge.h` (auto-generated by
//! `build.rs` via cbindgen). The Monado-side ALVR driver living in
//! `openxr/src/xrt/drivers/alvr/` loads this cdylib and calls into the
//! functions declared here.
//!
//! ## Current status (Phase 3.1.2 of openxr-migration.md)
//!
//! Live:
//!   - [`alvr_oxr_init`] / [`alvr_oxr_shutdown`] — construct/drop a real
//!     `alvr_server_core::ServerCoreContext`, spawn an event-drain thread.
//!   - [`alvr_oxr_get_head_pose`] — reads the latest tracking sample via
//!     `context.get_device_motion(HEAD_ID, target)`.
//!   - [`alvr_oxr_poll_session_event`] — drains client-connect/disconnect
//!     events surfaced by the drain thread.
//!
//! Stubs awaiting later sub-slices:
//!   - [`alvr_oxr_get_hmd_info`] / [`alvr_oxr_get_controller_info`] — 3.1.3.
//!   - [`alvr_oxr_get_controller_state`] / [`alvr_oxr_set_haptic`] — 3.1.3.
//!   - [`alvr_oxr_submit_layers`] — Phase 3 Slice 3.2/3.3 (Vulkan-input NVENC).
//!
//! Nothing here is loaded by the OpenVR/SteamVR path; that remains the default
//! mode and is unaffected.

use alvr_common::{
    HEAD_ID, ViewParams, error, info,
    parking_lot::{Mutex, RwLock},
    warn,
};
use alvr_server_core::{ServerCoreContext, ServerCoreEvent};
use std::{
    ffi::{CStr, c_char},
    path::PathBuf,
    sync::{
        atomic::{AtomicBool, Ordering},
        mpsc,
    },
    thread,
    time::Duration,
};

// Shared state across the bridge surface. Mirrors the structure used by
// `alvr_server_openvr/src/lib.rs`.
//
// Phase 3.1.2 adds:
//   - LOCAL_VIEW_PARAMS:  written by the event-drain thread when
//                         ServerCoreEvent::LocalViewParams fires, read by
//                         future per-view APIs (xrLocateViews equivalent).
//   - SESSION_EVENTS_RX:  the queue alvr_oxr_poll_session_event drains —
//                         populated by the event-drain thread for
//                         ClientConnected / ClientDisconnected etc.
//   - EVENT_THREAD:       JoinHandle for the drain thread spawned in init.
//   - SHUTDOWN_FLAG:      cooperative-shutdown signal so the drain loop
//                         exits on alvr_oxr_shutdown without waiting for
//                         a Disconnected error.
//
// EVENTS_RECEIVER is no longer parked in a static — alvr_oxr_init moves
// it directly into the spawned drain thread, which owns it for the
// thread's lifetime.
static SERVER_CORE_CONTEXT: RwLock<Option<ServerCoreContext>> = RwLock::new(None);
static LOCAL_VIEW_PARAMS: RwLock<[ViewParams; 2]> = RwLock::new([ViewParams::DUMMY; 2]);
static SESSION_EVENTS_RX: Mutex<Option<mpsc::Receiver<AlvrOxrEvent>>> = Mutex::new(None);
static EVENT_THREAD: Mutex<Option<thread::JoinHandle<()>>> = Mutex::new(None);
static SHUTDOWN_FLAG: AtomicBool = AtomicBool::new(false);

fn event_loop(
    events_receiver: mpsc::Receiver<ServerCoreEvent>,
    session_events_tx: mpsc::Sender<AlvrOxrEvent>,
) {
    // Recv timeout keeps the loop responsive to SHUTDOWN_FLAG without
    // wasting CPU. 50ms is a balance — short enough that shutdown
    // returns promptly, long enough that we're not spinning when idle.
    let recv_timeout = Duration::from_millis(50);

    while !SHUTDOWN_FLAG.load(Ordering::Acquire) {
        match events_receiver.recv_timeout(recv_timeout) {
            Ok(event) => match event {
                ServerCoreEvent::ClientConnected => {
                    let _ = session_events_tx.send(AlvrOxrEvent {
                        event_type: AlvrOxrEventType::StateChange,
                        timestamp_ns: 0,
                        // data[0] = 1 marks "connected"; the Monado-side
                        // driver compares against this constant. Schema
                        // will firm up in 3.1.4 when the bridge ABI is
                        // re-spec'd against real consumers.
                        data: [1, 0, 0, 0],
                    });
                }
                ServerCoreEvent::ClientDisconnected | ServerCoreEvent::ShutdownPending => {
                    let _ = session_events_tx.send(AlvrOxrEvent {
                        event_type: AlvrOxrEventType::ConnectionLost,
                        timestamp_ns: 0,
                        data: [0; 4],
                    });
                }
                ServerCoreEvent::LocalViewParams(params) => {
                    *LOCAL_VIEW_PARAMS.write() = params;
                }
                // Other events are drained but not yet routed.
                //   - Tracking / Buttons:  read on-demand by
                //     alvr_oxr_get_head_pose / _controller_state via
                //     context.get_device_motion (Tracking) and (3.1.3+)
                //     via context state for Buttons.
                //   - SetOpenvrProperty:   irrelevant in OpenXR mode.
                //   - Battery / Playspace / etc.: 3.1.4+.
                _ => {}
            },
            Err(mpsc::RecvTimeoutError::Timeout) => continue,
            // Disconnected means ServerCoreContext was dropped — exit cleanly.
            Err(mpsc::RecvTimeoutError::Disconnected) => break,
        }
    }
}

/// Result codes returned across the FFI boundary. Mirrors `xrt_result_t`
/// loosely but is intentionally a separate enum so that the bridge ABI can
/// evolve independently of Monado.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrResult {
    /// Operation succeeded.
    Ok = 0,
    /// Operation is not yet implemented in this build of ALVR.
    NotImplemented = -1,
    /// Operation failed for an unspecified reason.
    Failed = -2,
    /// The OpenXR mode has not been initialised yet.
    NotInitialised = -3,
}

/// Per-side identifier for hand/controller bridge calls.
#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrSide {
    Left = 0,
    Right = 1,
}

/// Initialise the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process start (after Monado has loaded `libalvr_server_openxr`).
///
/// `root_dir` is the parent directory ALVR uses for `session.json`, log
/// output, and the embedded web server's working dir — the OpenXR-mode
/// analogue of the OpenVR driver root. The Monado-side driver typically
/// derives this from an env var (`ALVR_ROOT`) or from the path of the
/// loaded cdylib.
///
/// # Safety
/// `root_dir` must be a valid NUL-terminated UTF-8 C string. The bridge
/// must be called from a single thread before any other bridge function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_init(root_dir: *const c_char) -> AlvrOxrResult {
    if root_dir.is_null() {
        error!("alvr_oxr_init: root_dir is null");
        return AlvrOxrResult::Failed;
    }
    let root_dir = match unsafe { CStr::from_ptr(root_dir) }.to_str() {
        Ok(s) => PathBuf::from(s),
        Err(err) => {
            error!("alvr_oxr_init: root_dir is not valid UTF-8: {err}");
            return AlvrOxrResult::Failed;
        }
    };

    if SERVER_CORE_CONTEXT.read().is_some() {
        warn!("alvr_oxr_init: already initialised; ignoring duplicate call");
        return AlvrOxrResult::Ok;
    }

    let filesystem_layout = alvr_filesystem::Layout::new(&root_dir);
    alvr_server_core::initialize_environment(filesystem_layout.clone());

    let log_to_disk = alvr_server_core::settings().extra.logging.log_to_disk;
    alvr_server_core::init_logging(
        log_to_disk.then(|| filesystem_layout.session_log()),
        Some(filesystem_layout.crash_log()),
    );

    let (context, events_receiver) = ServerCoreContext::new();
    context.start_connection();

    let (session_events_tx, session_events_rx) = mpsc::channel::<AlvrOxrEvent>();
    SHUTDOWN_FLAG.store(false, Ordering::Release);
    let drain_thread = thread::Builder::new()
        .name("alvr_oxr_event_drain".to_owned())
        .spawn(move || event_loop(events_receiver, session_events_tx))
        .expect("failed to spawn alvr_oxr_event_drain thread");

    *SERVER_CORE_CONTEXT.write() = Some(context);
    *SESSION_EVENTS_RX.lock() = Some(session_events_rx);
    *EVENT_THREAD.lock() = Some(drain_thread);

    info!("alvr_oxr_init: OpenXR mode bridge ready (root_dir={root_dir:?})");
    AlvrOxrResult::Ok
}

/// Shut down the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process exit.
///
/// # Safety
/// Must be called after the last bridge call has returned.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_shutdown() {
    // Signal the drain thread to exit, then drop the context (which drops
    // the events_sender — the thread's recv will return Disconnected if
    // the timeout poll hadn't already exited it via SHUTDOWN_FLAG).
    SHUTDOWN_FLAG.store(true, Ordering::Release);

    if SERVER_CORE_CONTEXT.write().take().is_none() {
        warn!("alvr_oxr_shutdown: not initialised; ignoring");
        return;
    }

    if let Some(join) = EVENT_THREAD.lock().take()
        && let Err(err) = join.join()
    {
        error!("alvr_oxr_shutdown: drain thread panicked: {err:?}");
    }
    SESSION_EVENTS_RX.lock().take();

    info!("alvr_oxr_shutdown: OpenXR mode bridge torn down");
}

/// Fill `out_serial` with the HMD's serial string. `buf_len` is the caller's
/// buffer size; the bridge writes at most `buf_len - 1` bytes plus a NUL.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_hmd_info(
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    let _ = (out_serial, buf_len);
    warn!("alvr_oxr_get_hmd_info: not yet wired up");
    AlvrOxrResult::NotImplemented
}

/// Fill `out_serial` with the controller's serial string. See
/// [`alvr_oxr_get_hmd_info`] for the buffer contract.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_info(
    side: AlvrOxrSide,
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    let _ = (side, out_serial, buf_len);
    warn!("alvr_oxr_get_controller_info: not yet wired up");
    AlvrOxrResult::NotImplemented
}

/// Pose returned by the bridge. Coordinate convention follows OpenXR
/// (right-handed, +Y up, -Z forward).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrPose {
    pub position: [f32; 3],
    pub orientation: [f32; 4], // (x, y, z, w)
}

/// Query the predicted head pose at `at_timestamp_ns` (CLOCK_MONOTONIC ns).
///
/// # Safety
/// `out_pose` must be a writable `AlvrOxrPose`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_head_pose(
    at_timestamp_ns: i64,
    out_pose: *mut AlvrOxrPose,
) -> AlvrOxrResult {
    if out_pose.is_null() {
        return AlvrOxrResult::Failed;
    }
    unsafe { *out_pose = AlvrOxrPose::default() };

    let target = Duration::from_nanos(at_timestamp_ns.max(0) as u64);

    let Some(context) = &*SERVER_CORE_CONTEXT.read() else {
        return AlvrOxrResult::NotInitialised;
    };

    // get_device_motion returns the latest received tracking sample at or
    // before the requested timestamp. Phase 3.1.2 mirrors the OpenVR
    // pattern (server_openvr/src/lib.rs L96-L116) sans the explicit
    // predict() step — Monado already gives us a future predicted
    // timestamp, and an internal predict layer would require us to know
    // the source poll_timestamp. If timing accuracy turns out to need it,
    // a 3.1.5 follow-up can wire `motion.predict(now, target)` in.
    if let Some(motion) = context.get_device_motion(*HEAD_ID, target) {
        unsafe {
            *out_pose = AlvrOxrPose {
                position: motion.pose.position.to_array(),
                orientation: motion.pose.orientation.to_array(),
            };
        }
    }
    // No tracking yet (client hasn't connected, headset hasn't sent a
    // sample, etc.) → identity is fine; Monado treats Ok+identity as
    // "device present but uninitialised". Returning NotInitialised here
    // would make Monado disable the device.
    AlvrOxrResult::Ok
}

/// Per-frame controller state passed back over the bridge. Buttons and
/// analogue values mirror the OpenXR Touch profile layout. Fields will be
/// extended in Phase 3 as `alvr_packets::TrackingPacket` features are wired in.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrControllerState {
    pub pose: AlvrOxrPose,
    pub linear_velocity: [f32; 3],
    pub angular_velocity: [f32; 3],
    pub trigger: f32,
    pub squeeze: f32,
    pub thumbstick: [f32; 2],
    pub buttons: u32, // bitfield, see ALVR_OXR_BUTTON_* (to be defined)
}

/// Query the controller state at `at_timestamp_ns`.
///
/// # Safety
/// `out_state` must be a writable `AlvrOxrControllerState`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_state(
    side: AlvrOxrSide,
    at_timestamp_ns: i64,
    out_state: *mut AlvrOxrControllerState,
) -> AlvrOxrResult {
    let _ = (side, at_timestamp_ns);
    if !out_state.is_null() {
        unsafe { *out_state = AlvrOxrControllerState::default() };
    }
    AlvrOxrResult::NotImplemented
}

/// Haptic pulse parameters. Maps onto OpenXR `XrHapticVibration`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrHaptic {
    pub duration_ns: i64,
    pub frequency_hz: f32,
    pub amplitude: f32,
}

/// Trigger a haptic pulse on the given controller.
///
/// # Safety
/// `params` must point to a valid `AlvrOxrHaptic`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_set_haptic(
    side: AlvrOxrSide,
    params: *const AlvrOxrHaptic,
) -> AlvrOxrResult {
    let _ = (side, params);
    AlvrOxrResult::NotImplemented
}

/// One submitted OpenXR composition layer. The Monado-side compositor builds
/// an array of these and hands them to the bridge once per frame.
///
/// Image handles are platform-specific:
/// * Windows: `HANDLE` from a `D3D11_RESOURCE_MISC_SHARED_NTHANDLE` resource
///   or `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32` (`u64` of the HANDLE).
/// * Linux: DMABUF fd (cast to `u64`).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrLayer {
    pub layer_type: u32,           // see XRT_LAYER_*
    pub view_count: u32,
    pub image_handles: [u64; 2],   // left/right view, native handles
    pub width: u32,
    pub height: u32,
    pub fov_radians: [f32; 4],     // per view: [left, right, up, down]; primary view only
    pub pose: AlvrOxrPose,
}

/// Submit a frame's worth of composition layers.
///
/// # Safety
/// `layers` must point to `layer_count` valid `AlvrOxrLayer`s. `sync_handle`
/// may be 0 to indicate "no GPU sync, use a fence".
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_submit_layers(
    frame_id: i64,
    layer_count: u32,
    layers: *const AlvrOxrLayer,
    sync_handle: u64,
) -> AlvrOxrResult {
    let _ = (frame_id, layer_count, layers, sync_handle);
    AlvrOxrResult::NotImplemented
}

/// Session-event type discriminant. Mirrors `enum xrt_session_event_type`
/// loosely; trimmed down to what ALVR cares about.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrEventType {
    None = 0,
    StateChange = 1,
    ConnectionLost = 4,
    RefreshRateChange = 5,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrEvent {
    pub event_type: AlvrOxrEventType,
    pub timestamp_ns: i64,
    pub data: [i32; 4], // event-type-specific payload
}

/// Poll one session event from the bridge. Returns
/// [`AlvrOxrResult::Ok`] with `out_event.event_type == None` when the queue
/// is empty.
///
/// # Safety
/// `out_event` must be a writable `AlvrOxrEvent`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_poll_session_event(out_event: *mut AlvrOxrEvent) -> AlvrOxrResult {
    if out_event.is_null() {
        return AlvrOxrResult::Failed;
    }

    let mut event = AlvrOxrEvent {
        event_type: AlvrOxrEventType::None,
        timestamp_ns: 0,
        data: [0; 4],
    };

    if let Some(rx) = SESSION_EVENTS_RX.lock().as_ref()
        && let Ok(received) = rx.try_recv()
    {
        event = received;
    }

    unsafe { *out_event = event };
    AlvrOxrResult::Ok
}
