//! OpenXR (Monado) integration for the PC side of ALVR.
//!
//! This crate is the OpenXR analogue of `alvr_server_openvr`. It exports the
//! C ABI defined in `include/alvr_runtime_bridge.h` (auto-generated by
//! `build.rs` via cbindgen). The Monado-side ALVR driver living in
//! `openxr/src/xrt/drivers/alvr/` loads this cdylib and calls into the
//! functions declared here.
//!
//! ## Current status (Phase 1 of openxr-migration.md)
//!
//! All entrypoints return [`AlvrOxrResult::NotImplemented`] and log a warning.
//! Wiring them up to `alvr_server_core` happens in Phase 3 — see the migration
//! plan at `openxr-migration.md` for the order of operations.
//!
//! Nothing here is loaded by the OpenVR/SteamVR path; that remains the default
//! mode and is unaffected.

use alvr_common::{info, warn};
use std::ffi::c_char;

/// Result codes returned across the FFI boundary. Mirrors `xrt_result_t`
/// loosely but is intentionally a separate enum so that the bridge ABI can
/// evolve independently of Monado.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrResult {
    /// Operation succeeded.
    Ok = 0,
    /// Operation is not yet implemented in this build of ALVR.
    NotImplemented = -1,
    /// Operation failed for an unspecified reason.
    Failed = -2,
    /// The OpenXR mode has not been initialised yet.
    NotInitialised = -3,
}

/// Per-side identifier for hand/controller bridge calls.
#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrSide {
    Left = 0,
    Right = 1,
}

/// Initialise the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process start (after Monado has loaded `libalvr_server_openxr`).
///
/// # Safety
/// Must be called from a single thread before any other bridge function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_init() -> AlvrOxrResult {
    info!("alvr_oxr_init: OpenXR mode bridge stub initialised");
    // TODO(phase-3): construct an alvr_server_core::ServerCoreContext here
    // and store it in a Once/OnceLock.
    AlvrOxrResult::Ok
}

/// Shut down the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process exit.
///
/// # Safety
/// Must be called after the last bridge call has returned.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_shutdown() {
    info!("alvr_oxr_shutdown: OpenXR mode bridge stub shut down");
    // TODO(phase-3): drop the ServerCoreContext.
}

/// Fill `out_serial` with the HMD's serial string. `buf_len` is the caller's
/// buffer size; the bridge writes at most `buf_len - 1` bytes plus a NUL.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_hmd_info(
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    let _ = (out_serial, buf_len);
    warn!("alvr_oxr_get_hmd_info: not yet wired up");
    AlvrOxrResult::NotImplemented
}

/// Fill `out_serial` with the controller's serial string. See
/// [`alvr_oxr_get_hmd_info`] for the buffer contract.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_info(
    side: AlvrOxrSide,
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    let _ = (side, out_serial, buf_len);
    warn!("alvr_oxr_get_controller_info: not yet wired up");
    AlvrOxrResult::NotImplemented
}

/// Pose returned by the bridge. Coordinate convention follows OpenXR
/// (right-handed, +Y up, -Z forward).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrPose {
    pub position: [f32; 3],
    pub orientation: [f32; 4], // (x, y, z, w)
}

/// Query the predicted head pose at `at_timestamp_ns` (CLOCK_MONOTONIC ns).
///
/// # Safety
/// `out_pose` must be a writable `AlvrOxrPose`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_head_pose(
    at_timestamp_ns: i64,
    out_pose: *mut AlvrOxrPose,
) -> AlvrOxrResult {
    let _ = at_timestamp_ns;
    if !out_pose.is_null() {
        unsafe { *out_pose = AlvrOxrPose::default() };
    }
    AlvrOxrResult::NotImplemented
}

/// Per-frame controller state passed back over the bridge. Buttons and
/// analogue values mirror the OpenXR Touch profile layout. Fields will be
/// extended in Phase 3 as `alvr_packets::TrackingPacket` features are wired in.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrControllerState {
    pub pose: AlvrOxrPose,
    pub linear_velocity: [f32; 3],
    pub angular_velocity: [f32; 3],
    pub trigger: f32,
    pub squeeze: f32,
    pub thumbstick: [f32; 2],
    pub buttons: u32, // bitfield, see ALVR_OXR_BUTTON_* (to be defined)
}

/// Query the controller state at `at_timestamp_ns`.
///
/// # Safety
/// `out_state` must be a writable `AlvrOxrControllerState`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_state(
    side: AlvrOxrSide,
    at_timestamp_ns: i64,
    out_state: *mut AlvrOxrControllerState,
) -> AlvrOxrResult {
    let _ = (side, at_timestamp_ns);
    if !out_state.is_null() {
        unsafe { *out_state = AlvrOxrControllerState::default() };
    }
    AlvrOxrResult::NotImplemented
}

/// Haptic pulse parameters. Maps onto OpenXR `XrHapticVibration`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrHaptic {
    pub duration_ns: i64,
    pub frequency_hz: f32,
    pub amplitude: f32,
}

/// Trigger a haptic pulse on the given controller.
///
/// # Safety
/// `params` must point to a valid `AlvrOxrHaptic`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_set_haptic(
    side: AlvrOxrSide,
    params: *const AlvrOxrHaptic,
) -> AlvrOxrResult {
    let _ = (side, params);
    AlvrOxrResult::NotImplemented
}

/// One submitted OpenXR composition layer. The Monado-side compositor builds
/// an array of these and hands them to the bridge once per frame.
///
/// Image handles are platform-specific:
/// * Windows: `HANDLE` from a `D3D11_RESOURCE_MISC_SHARED_NTHANDLE` resource
///   or `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32` (`u64` of the HANDLE).
/// * Linux: DMABUF fd (cast to `u64`).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrLayer {
    pub layer_type: u32,           // see XRT_LAYER_*
    pub view_count: u32,
    pub image_handles: [u64; 2],   // left/right view, native handles
    pub width: u32,
    pub height: u32,
    pub fov_radians: [f32; 4],     // per view: [left, right, up, down]; primary view only
    pub pose: AlvrOxrPose,
}

/// Submit a frame's worth of composition layers.
///
/// # Safety
/// `layers` must point to `layer_count` valid `AlvrOxrLayer`s. `sync_handle`
/// may be 0 to indicate "no GPU sync, use a fence".
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_submit_layers(
    frame_id: i64,
    layer_count: u32,
    layers: *const AlvrOxrLayer,
    sync_handle: u64,
) -> AlvrOxrResult {
    let _ = (frame_id, layer_count, layers, sync_handle);
    AlvrOxrResult::NotImplemented
}

/// Session-event type discriminant. Mirrors `enum xrt_session_event_type`
/// loosely; trimmed down to what ALVR cares about.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrEventType {
    None = 0,
    StateChange = 1,
    ConnectionLost = 4,
    RefreshRateChange = 5,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrEvent {
    pub event_type: AlvrOxrEventType,
    pub timestamp_ns: i64,
    pub data: [i32; 4], // event-type-specific payload
}

/// Poll one session event from the bridge. Returns
/// [`AlvrOxrResult::Ok`] with `out_event.event_type == None` when the queue
/// is empty.
///
/// # Safety
/// `out_event` must be a writable `AlvrOxrEvent`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_poll_session_event(out_event: *mut AlvrOxrEvent) -> AlvrOxrResult {
    if !out_event.is_null() {
        unsafe {
            *out_event = AlvrOxrEvent {
                event_type: AlvrOxrEventType::None,
                timestamp_ns: 0,
                data: [0; 4],
            }
        };
    }
    AlvrOxrResult::Ok
}
