//! OpenXR (Monado) integration for the PC side of ALVR.
//!
//! This crate is the OpenXR analogue of `alvr_server_openvr`. It exports the
//! C ABI defined in `include/alvr_runtime_bridge.h` (auto-generated by
//! `build.rs` via cbindgen). The Monado-side ALVR driver living in
//! `openxr/src/xrt/drivers/alvr/` loads this cdylib and calls into the
//! functions declared here.
//!
//! ## Current status (Phase 3.1.5 of openxr-migration.md)
//!
//! Live:
//!   - [`alvr_oxr_init`] / [`alvr_oxr_shutdown`] — construct/drop a real
//!     `alvr_server_core::ServerCoreContext`, spawn an event-drain thread.
//!   - [`alvr_oxr_get_head_pose`] / [`alvr_oxr_get_controller_state`] —
//!     latest tracking sample via `context.get_device_motion`. Controller
//!     state also returns trigger / squeeze / thumbstick / button
//!     bitfield from a cache the drain thread maintains on
//!     `ServerCoreEvent::Buttons`.
//!   - [`alvr_oxr_get_view_params`] — per-eye pose + FOV from the
//!     `LOCAL_VIEW_PARAMS` cache the drain thread maintains on
//!     `ServerCoreEvent::LocalViewParams`.
//!   - [`alvr_oxr_set_haptic`] — forwards to `context.send_haptics`.
//!   - [`alvr_oxr_get_hmd_info`] / [`alvr_oxr_get_controller_info`] —
//!     write stable bridge-side serials (`ALVR_HMD`, `ALVR_Controller_*`).
//!   - [`alvr_oxr_poll_session_event`] — drains client-connect/disconnect
//!     events surfaced by the drain thread.
//!   - [`alvr_oxr_get_hand_skeleton`] — per-side 26-joint skeleton via
//!     `ServerCoreContext::get_hand_skeleton`; tracked iff the client sent a
//!     hand sample for the resolved frame (Phase 7 hand-tracking passthrough,
//!     ABI v4).
//!   - [`alvr_oxr_get_foveation`] / [`alvr_oxr_set_foveation`] — RwLock-backed
//!     cache of per-view foveation params; getter is the encoder hot-path
//!     read, setter is the drain thread's `ServerCoreEvent::PerViewFoveation`
//!     consumer (Phase 7 per-view foveation Slice 1, ABI v5).
//!   - [`alvr_oxr_get_foveation_vars`] — static FFR compress params (foveated
//!     output resolution + `ffr.comp` spec constants) derived from the
//!     negotiated `openvr_config`, for `comp_alvr`'s server-side foveation
//!     compress pass (OpenXR FFR Slice 1, ABI v8).
//!
//! Only stub left:
//!   - [`alvr_oxr_submit_layers`] — Phase 3 Slice 3.2/3.3
//!     (Vulkan-input NVENC; needs Vulkan SDK + NVENC 12.1+ + Monado).
//!
//! Nothing here is loaded by the OpenVR/SteamVR path; that remains the default
//! mode and is unaffected.

use alvr_common::{
    BUTTON_INFO, HAND_LEFT_ID, HAND_RIGHT_ID, HEAD_ID, LEFT_A_CLICK_ID, LEFT_A_TOUCH_ID,
    LEFT_B_CLICK_ID, LEFT_B_TOUCH_ID, LEFT_MENU_CLICK_ID, LEFT_SQUEEZE_CLICK_ID,
    LEFT_SQUEEZE_VALUE_ID, LEFT_SYSTEM_CLICK_ID, LEFT_THUMBREST_TOUCH_ID, LEFT_THUMBSTICK_CLICK_ID,
    LEFT_THUMBSTICK_TOUCH_ID, LEFT_THUMBSTICK_X_ID, LEFT_THUMBSTICK_Y_ID, LEFT_TRIGGER_CLICK_ID,
    LEFT_TRIGGER_TOUCH_ID, LEFT_TRIGGER_VALUE_ID, LEFT_X_CLICK_ID, LEFT_X_TOUCH_ID,
    LEFT_Y_CLICK_ID, LEFT_Y_TOUCH_ID, RIGHT_A_CLICK_ID, RIGHT_A_TOUCH_ID, RIGHT_B_CLICK_ID,
    RIGHT_B_TOUCH_ID, RIGHT_MENU_CLICK_ID, RIGHT_SQUEEZE_CLICK_ID, RIGHT_SQUEEZE_VALUE_ID,
    RIGHT_SYSTEM_CLICK_ID, RIGHT_THUMBREST_TOUCH_ID, RIGHT_THUMBSTICK_CLICK_ID,
    RIGHT_THUMBSTICK_TOUCH_ID, RIGHT_THUMBSTICK_X_ID, RIGHT_THUMBSTICK_Y_ID,
    RIGHT_TRIGGER_CLICK_ID, RIGHT_TRIGGER_TOUCH_ID, RIGHT_TRIGGER_VALUE_ID, RIGHT_X_CLICK_ID,
    RIGHT_X_TOUCH_ID, RIGHT_Y_CLICK_ID, RIGHT_Y_TOUCH_ID, ViewParams, error,
    glam::UVec2,
    info,
    parking_lot::{Mutex, RwLock},
    warn,
};
use alvr_packets::{BatteryInfo, ButtonValue, Haptics};
use alvr_server_core::{HandType, PerViewFoveationView, ServerCoreContext, ServerCoreEvent};
use alvr_session::{FoveatedEncodingConfig, foveation_compress_vars, settings_schema::Switch};
use std::{
    ffi::{CStr, c_char},
    path::PathBuf,
    ptr,
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        mpsc,
    },
    thread,
    time::Duration,
};

/// Copy a NUL-terminated UTF-8 string into a caller-provided buffer. Truncates
/// to fit `buf_len - 1` bytes plus the trailing NUL. Returns Ok on success,
/// Failed when out_serial is NULL or buf_len is 0.
fn write_c_string(out: *mut c_char, buf_len: usize, value: &str) -> AlvrOxrResult {
    if out.is_null() || buf_len == 0 {
        return AlvrOxrResult::Failed;
    }
    let bytes = value.as_bytes();
    let copy_len = bytes.len().min(buf_len - 1);
    unsafe {
        ptr::copy_nonoverlapping(bytes.as_ptr() as *const c_char, out, copy_len);
        *out.add(copy_len) = 0;
    }
    AlvrOxrResult::Ok
}

/// Per-controller device-ID lookup. Independent of [`AlvrOxrSide`]'s discriminant
/// so the bridge ABI can change without affecting the device-ID mapping.
fn side_device_id(side: AlvrOxrSide) -> u64 {
    match side {
        AlvrOxrSide::Left => *HAND_LEFT_ID,
        AlvrOxrSide::Right => *HAND_RIGHT_ID,
    }
}

// Shared state across the bridge surface. Mirrors the structure used by
// `alvr_server_openvr/src/lib.rs`.
//
// Phase 3.1.2 adds:
//   - LOCAL_VIEW_PARAMS:  written by the event-drain thread when
//                         ServerCoreEvent::LocalViewParams fires, read by
//                         future per-view APIs (xrLocateViews equivalent).
//   - SESSION_EVENTS_RX:  the queue alvr_oxr_poll_session_event drains —
//                         populated by the event-drain thread for
//                         ClientConnected / ClientDisconnected etc.
//   - EVENT_THREAD:       JoinHandle for the drain thread spawned in init.
//   - SHUTDOWN_FLAG:      cooperative-shutdown signal so the drain loop
//                         exits on alvr_oxr_shutdown without waiting for
//                         a Disconnected error.
//
// EVENTS_RECEIVER is no longer parked in a static — alvr_oxr_init moves
// it directly into the spawned drain thread, which owns it for the
// thread's lifetime.
static SERVER_CORE_CONTEXT: RwLock<Option<ServerCoreContext>> = RwLock::new(None);
static LOCAL_VIEW_PARAMS: RwLock<[ViewParams; 2]> = RwLock::new([ViewParams::DUMMY; 2]);
static SESSION_EVENTS_RX: Mutex<Option<mpsc::Receiver<AlvrOxrEvent>>> = Mutex::new(None);
static EVENT_THREAD: Mutex<Option<thread::JoinHandle<()>>> = Mutex::new(None);
static SHUTDOWN_FLAG: AtomicBool = AtomicBool::new(false);

/// Latest client tracking `poll_timestamp` (nanoseconds), updated by the drain
/// thread on `ServerCoreEvent::Tracking`. The encoder stamps each video frame
/// with this so the client can correlate the decoded frame to a pose it sent —
/// the client's clock, NOT Monado's compositor display time (there is no
/// client↔server clock sync, so a Monado timestamp matches nothing and the
/// client discards every frame, showing black). 0 = no tracking received yet.
static LATEST_POLL_TIMESTAMP_NS: AtomicU64 = AtomicU64::new(0);

/// Cached analogue + button state for one side. Indexed by AlvrOxrSide
/// discriminant (Left = 0, Right = 1). Written by the event-drain thread on
/// `ServerCoreEvent::Buttons`, read by [`alvr_oxr_get_controller_state`].
#[derive(Clone, Copy)]
struct TouchAnalog {
    trigger: f32,
    squeeze: f32,
    thumbstick: [f32; 2],
    buttons: u32,
}

const TOUCH_ANALOG_INIT: TouchAnalog = TouchAnalog {
    trigger: 0.0,
    squeeze: 0.0,
    thumbstick: [0.0; 2],
    buttons: 0,
};

static CONTROLLER_BUTTON_CACHE: Mutex<[TouchAnalog; 2]> = Mutex::new([TOUCH_ANALOG_INIT; 2]);

/// Translate a button path ID + value into the appropriate cache field
/// update. Unmapped paths are silently ignored — the Touch profile bridge
/// surface intentionally covers a subset; trackpad/back/sensor sub-paths
/// are dropped on the floor here because no current consumer maps them.
fn apply_button(state: &mut TouchAnalog, path_id: u64, value: ButtonValue) {
    match value {
        ButtonValue::Scalar(v) => {
            if path_id == *LEFT_TRIGGER_VALUE_ID || path_id == *RIGHT_TRIGGER_VALUE_ID {
                state.trigger = v;
            } else if path_id == *LEFT_SQUEEZE_VALUE_ID || path_id == *RIGHT_SQUEEZE_VALUE_ID {
                state.squeeze = v;
            } else if path_id == *LEFT_THUMBSTICK_X_ID || path_id == *RIGHT_THUMBSTICK_X_ID {
                state.thumbstick[0] = v;
            } else if path_id == *LEFT_THUMBSTICK_Y_ID || path_id == *RIGHT_THUMBSTICK_Y_ID {
                state.thumbstick[1] = v;
            }
        }
        ButtonValue::Binary(pressed) => {
            let mask = button_bit_for(path_id);
            if mask != 0 {
                if pressed {
                    state.buttons |= mask;
                } else {
                    state.buttons &= !mask;
                }
            }
        }
    }
}

/// Maps a binary-button path ID to the corresponding `ALVR_OXR_BUTTON_*`
/// bit, or 0 if the path isn't in the bridge's bit table. Both sides share
/// the same bit positions (each side's path IDs are distinct), so callers
/// must already have routed to the right slot via `BUTTON_INFO.device_id`
/// before consulting this map.
fn button_bit_for(path_id: u64) -> u32 {
    if path_id == *LEFT_A_CLICK_ID || path_id == *RIGHT_A_CLICK_ID {
        ALVR_OXR_BUTTON_A_CLICK
    } else if path_id == *LEFT_A_TOUCH_ID || path_id == *RIGHT_A_TOUCH_ID {
        ALVR_OXR_BUTTON_A_TOUCH
    } else if path_id == *LEFT_B_CLICK_ID || path_id == *RIGHT_B_CLICK_ID {
        ALVR_OXR_BUTTON_B_CLICK
    } else if path_id == *LEFT_B_TOUCH_ID || path_id == *RIGHT_B_TOUCH_ID {
        ALVR_OXR_BUTTON_B_TOUCH
    } else if path_id == *LEFT_X_CLICK_ID || path_id == *RIGHT_X_CLICK_ID {
        ALVR_OXR_BUTTON_X_CLICK
    } else if path_id == *LEFT_X_TOUCH_ID || path_id == *RIGHT_X_TOUCH_ID {
        ALVR_OXR_BUTTON_X_TOUCH
    } else if path_id == *LEFT_Y_CLICK_ID || path_id == *RIGHT_Y_CLICK_ID {
        ALVR_OXR_BUTTON_Y_CLICK
    } else if path_id == *LEFT_Y_TOUCH_ID || path_id == *RIGHT_Y_TOUCH_ID {
        ALVR_OXR_BUTTON_Y_TOUCH
    } else if path_id == *LEFT_MENU_CLICK_ID || path_id == *RIGHT_MENU_CLICK_ID {
        ALVR_OXR_BUTTON_MENU_CLICK
    } else if path_id == *LEFT_SYSTEM_CLICK_ID || path_id == *RIGHT_SYSTEM_CLICK_ID {
        ALVR_OXR_BUTTON_SYSTEM_CLICK
    } else if path_id == *LEFT_THUMBSTICK_CLICK_ID || path_id == *RIGHT_THUMBSTICK_CLICK_ID {
        ALVR_OXR_BUTTON_THUMBSTICK_CLICK
    } else if path_id == *LEFT_THUMBSTICK_TOUCH_ID || path_id == *RIGHT_THUMBSTICK_TOUCH_ID {
        ALVR_OXR_BUTTON_THUMBSTICK_TOUCH
    } else if path_id == *LEFT_TRIGGER_CLICK_ID || path_id == *RIGHT_TRIGGER_CLICK_ID {
        ALVR_OXR_BUTTON_TRIGGER_CLICK
    } else if path_id == *LEFT_TRIGGER_TOUCH_ID || path_id == *RIGHT_TRIGGER_TOUCH_ID {
        ALVR_OXR_BUTTON_TRIGGER_TOUCH
    } else if path_id == *LEFT_SQUEEZE_CLICK_ID || path_id == *RIGHT_SQUEEZE_CLICK_ID {
        ALVR_OXR_BUTTON_SQUEEZE_CLICK
    } else if path_id == *LEFT_THUMBREST_TOUCH_ID || path_id == *RIGHT_THUMBREST_TOUCH_ID {
        ALVR_OXR_BUTTON_THUMBREST_TOUCH
    } else {
        0
    }
}

fn event_loop(
    events_receiver: mpsc::Receiver<ServerCoreEvent>,
    session_events_tx: mpsc::Sender<AlvrOxrEvent>,
) {
    // Recv timeout keeps the loop responsive to SHUTDOWN_FLAG without
    // wasting CPU. 50ms is a balance — short enough that shutdown
    // returns promptly, long enough that we're not spinning when idle.
    let recv_timeout = Duration::from_millis(50);

    while !SHUTDOWN_FLAG.load(Ordering::Acquire) {
        match events_receiver.recv_timeout(recv_timeout) {
            Ok(event) => match event {
                ServerCoreEvent::ClientConnected => {
                    // Stand up the NVENC encoder from the now-negotiated
                    // openvr_config and publish the sequence-header NALs. No-op
                    // (logs) if NVENC/CUDA is unavailable. Mirrors the OpenVR
                    // side's InitializeStreaming on ClientConnected.
                    encoder_bridge::start();
                    let _ = session_events_tx.send(AlvrOxrEvent {
                        event_type: AlvrOxrEventType::StateChange,
                        timestamp_ns: 0,
                        // data[0] = 1 marks "connected"; the Monado-side
                        // driver compares against this constant. Schema
                        // will firm up in 3.1.4 when the bridge ABI is
                        // re-spec'd against real consumers.
                        data: [1, 0, 0, 0],
                    });
                }
                ServerCoreEvent::ClientDisconnected | ServerCoreEvent::ShutdownPending => {
                    encoder_bridge::stop();
                    let _ = session_events_tx.send(AlvrOxrEvent {
                        event_type: AlvrOxrEventType::ConnectionLost,
                        timestamp_ns: 0,
                        data: [0; 4],
                    });
                }
                ServerCoreEvent::LocalViewParams(params) => {
                    *LOCAL_VIEW_PARAMS.write() = params;
                }
                ServerCoreEvent::PerViewFoveation(views) => {
                    // Translate server_core's per-axis view into the bridge
                    // cache shape (which adds the `is_present` flag for the
                    // encoder's "encode at full resolution" fast path).
                    *FOVEATION.write() = [
                        per_view_to_bridge(&views[0]),
                        per_view_to_bridge(&views[1]),
                    ];
                }
                ServerCoreEvent::Buttons(entries) => {
                    // Route each entry by device_id from BUTTON_INFO.
                    // Entries for non-controller devices (HMD path buttons
                    // etc.) are silently dropped — the bridge surface only
                    // exposes left/right controller analogues.
                    let mut cache = CONTROLLER_BUTTON_CACHE.lock();
                    for entry in entries {
                        let Some(info) = BUTTON_INFO.get(&entry.path_id) else { continue };
                        let slot = if info.device_id == *HAND_LEFT_ID {
                            0
                        } else if info.device_id == *HAND_RIGHT_ID {
                            1
                        } else {
                            continue;
                        };
                        apply_button(&mut cache[slot], entry.path_id, entry.value);
                    }
                }
                ServerCoreEvent::Battery(info) => {
                    if let Some(data) = encode_battery(&info) {
                        let _ = session_events_tx.send(AlvrOxrEvent {
                            event_type: AlvrOxrEventType::Battery,
                            timestamp_ns: 0,
                            data,
                        });
                    }
                    // Devices not in the kind table (body trackers etc.) are
                    // dropped silently — the bridge ABI doesn't surface them.
                }
                ServerCoreEvent::Tracking { poll_timestamp } => {
                    // The poses themselves are read on-demand via
                    // get_device_motion; here we only stash the client's frame
                    // timestamp so the encoder can stamp video with it (the
                    // client correlates decoded frames by this exact value).
                    LATEST_POLL_TIMESTAMP_NS
                        .store(poll_timestamp.as_nanos() as u64, Ordering::Relaxed);
                }
                // Other events are drained but not yet routed.
                //   - SetOpenvrProperty:  irrelevant in OpenXR mode.
                //   - RefreshRate:        no upstream ServerCoreEvent variant
                //                         exists today — refresh-rate is
                //                         negotiated once at connection time.
                //                         The bridge ABI keeps
                //                         AlvrOxrEventType::RefreshRateChange
                //                         reserved for when one lands.
                //   - Playspace / ProximityState: not yet on the bridge
                //                         surface; defer until a Monado-side
                //                         consumer needs them.
                _ => {}
            },
            Err(mpsc::RecvTimeoutError::Timeout) => continue,
            // Disconnected means ServerCoreContext was dropped — exit cleanly.
            Err(mpsc::RecvTimeoutError::Disconnected) => break,
        }
    }
}

/// Bridge ABI version. Bump this **and** the matching expectation in the
/// Monado-side ALVR driver (`openxr/src/xrt/drivers/alvr/alvr_hub.c`'s
/// `ALVR_OXR_BRIDGE_ABI_EXPECTED`) on every incompatible change to the
/// surface defined below — added/removed/reordered exports, changed struct
/// layouts, changed enum discriminants, changed argument lists, semantic
/// changes to existing calls.
///
/// Initial value `1`. Increment monotonically; do not reuse old values.
///
/// At driver init the Monado side calls [`alvr_oxr_get_bridge_abi_version`]
/// and compares against the macro cbindgen emits for this const. A mismatch
/// means the loaded `alvr_server_openxr` cdylib was built against a
/// different bridge surface than the driver's compiled header expected
/// (typically: somebody rebuilt one half without bumping the submodule
/// pointer for the other half).
///
/// History:
/// - v1: initial surface (Phase 3.1 / 3.2).
/// - v2: added [`alvr_oxr_report_pacing`] so the Monado-side compositor can
///   forward per-frame `u_pc_*` timing data into `alvr_server_core`'s
///   metrics exporter (Phase 5 telemetry bridge).
/// - v3: added [`alvr_oxr_report_layer_types`] so the compositor can report
///   per-frame counts of submitted non-projection layer types (quad /
///   cylinder / equirect / cube / passthrough) that the runtime currently
///   drops (Phase 7 Slice 1; diagnostic before quad rasterisation lands).
/// - v4: added [`alvr_oxr_get_hand_skeleton`] + [`AlvrOxrHandJoint`] +
///   [`ALVR_OXR_HAND_JOINT_COUNT`] so the Monado-side ALVR driver can answer
///   `XR_EXT_hand_tracking` queries from the client's existing 26-joint
///   skeleton, sourced via `ServerCoreContext::get_hand_skeleton` (Phase 7
///   hand-tracking passthrough — alvr-side Slices 1 + 3; the Monado-side
///   `xrt_device::get_hand_tracking` lands as Slice 2 on the fork branch).
/// - v5: added [`alvr_oxr_get_foveation`] + [`alvr_oxr_set_foveation`] +
///   [`AlvrOxrFoveationView`] so the OpenXR-mode encoder can consume per-view
///   foveation params and the `server_core` drain thread can update them
///   per-frame from an eye-tracking-driven worker or a future
///   `RealTimeConfig.per_view_foveation` field (Phase 7 per-view foveation
///   Slice 1 — bridge surface only; encoder body still hardware-blocked,
///   `server_core` glue is Slice 3).
/// - v6: the NVENC encoder body landed (Slice 3.3). `AlvrOxrLayer` gains
///   `image_sizes[2]` (each view's backing allocation size, required by
///   `cuImportExternalMemory`), and [`alvr_oxr_submit_layers`] gains a
///   `display_time_ns` argument (the frame's predicted display time, so encoded
///   NALs carry the timestamp the client matches a pose against). Both are
///   filled by the Monado-side `comp_alvr`.
/// - v7: added [`alvr_oxr_get_view_resolution`] so the Monado-side HMD +
///   compositor advertise/allocate at the *negotiated* per-eye streaming
///   resolution (`openvr_config.eye_resolution`) instead of a hardcoded value.
///   Makes the OpenXR resolution pipeline coherent end to end (app render →
///   scratch → NVENC frame → client decode all agree), so the encoded frame is
///   fully filled and the client decodes/presents the stream.
/// - v8: added [`alvr_oxr_get_foveation_vars`] + [`AlvrOxrFoveationVars`] so the
///   Monado-side `comp_alvr` can run the server-side FFR (foveated-encoding)
///   compress pass. Returns the 32-aligned foveated per-eye resolution the
///   encoder must size to, plus the eight `ffr.comp` specialization constants
///   (`eyeSizeRatio`, `centerSize`, `centerShift`, `edgeRatio`), computed from
///   the negotiated `openvr_config` foveation params via
///   `alvr_session::foveation_compress_vars` — the exact inverse of the math
///   the client de-foveates with, so the round-trip matches. `enabled = false`
///   (foveation off session-wide) means "encode at full resolution, skip the
///   FFR pass" (OpenXR FFR Slice 1).
pub const ALVR_OXR_BRIDGE_ABI_VERSION: u32 = 8;

/// Return the bridge ABI version baked into this cdylib at compile time.
/// See [`ALVR_OXR_BRIDGE_ABI_VERSION`].
///
/// # Safety
/// Always safe to call; no preconditions, no shared state touched.
#[unsafe(no_mangle)]
pub extern "C" fn alvr_oxr_get_bridge_abi_version() -> u32 {
    ALVR_OXR_BRIDGE_ABI_VERSION
}

/// Negotiated per-eye streaming resolution (`openvr_config.eye_resolution`), in
/// pixels. The Monado-side HMD + compositor use this for the advertised view
/// config, the squasher scratch extent, and the HMD display extents, so the
/// whole OpenXR pipeline (app render → scratch → NVENC frame → client decode)
/// runs at the resolution the client negotiated and the encoder produces —
/// otherwise the encoded frame is partially filled / mis-sized and the client
/// can't present it.
///
/// Before any client has connected, `openvr_config` holds the value persisted
/// from the previous session (or the schema default) — still sane for
/// advertising the static OpenXR view config at startup.
///
/// # Safety
/// `out_width` and `out_height` must be writable `u32`s.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_view_resolution(
    out_width: *mut u32,
    out_height: *mut u32,
) -> AlvrOxrResult {
    if out_width.is_null() || out_height.is_null() {
        return AlvrOxrResult::Failed;
    }
    let oc = alvr_server_core::openvr_config();
    // # Safety: caller guarantees both pointers are writable.
    unsafe {
        *out_width = oc.eye_resolution_width;
        *out_height = oc.eye_resolution_height;
    }
    AlvrOxrResult::Ok
}

/// Result codes returned across the FFI boundary. Mirrors `xrt_result_t`
/// loosely but is intentionally a separate enum so that the bridge ABI can
/// evolve independently of Monado.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrResult {
    /// Operation succeeded.
    Ok = 0,
    /// Operation is not yet implemented in this build of ALVR.
    NotImplemented = -1,
    /// Operation failed for an unspecified reason.
    Failed = -2,
    /// The OpenXR mode has not been initialised yet.
    NotInitialised = -3,
}

/// Per-side identifier for hand/controller bridge calls.
#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrSide {
    Left = 0,
    Right = 1,
}

/// Initialise the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process start (after Monado has loaded `libalvr_server_openxr`).
///
/// `root_dir` is the parent directory ALVR uses for `session.json`, log
/// output, and the embedded web server's working dir — the OpenXR-mode
/// analogue of the OpenVR driver root. The Monado-side driver typically
/// derives this from an env var (`ALVR_ROOT`) or from the path of the
/// loaded cdylib.
///
/// # Safety
/// `root_dir` must be a valid NUL-terminated UTF-8 C string. The bridge
/// must be called from a single thread before any other bridge function.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_init(root_dir: *const c_char) -> AlvrOxrResult {
    if root_dir.is_null() {
        error!("alvr_oxr_init: root_dir is null");
        return AlvrOxrResult::Failed;
    }
    let root_dir = match unsafe { CStr::from_ptr(root_dir) }.to_str() {
        Ok(s) => PathBuf::from(s),
        Err(err) => {
            error!("alvr_oxr_init: root_dir is not valid UTF-8: {err}");
            return AlvrOxrResult::Failed;
        }
    };

    if SERVER_CORE_CONTEXT.read().is_some() {
        warn!("alvr_oxr_init: already initialised; ignoring duplicate call");
        return AlvrOxrResult::Ok;
    }

    let filesystem_layout = alvr_filesystem::Layout::new(&root_dir);
    alvr_server_core::initialize_environment(filesystem_layout.clone());

    let log_to_disk = alvr_server_core::settings().extra.logging.log_to_disk;
    alvr_server_core::init_logging(
        log_to_disk.then(|| filesystem_layout.session_log()),
        Some(filesystem_layout.crash_log()),
    );

    let (context, events_receiver) = ServerCoreContext::new();
    context.start_connection();

    let (session_events_tx, session_events_rx) = mpsc::channel::<AlvrOxrEvent>();
    SHUTDOWN_FLAG.store(false, Ordering::Release);
    let drain_thread = thread::Builder::new()
        .name("alvr_oxr_event_drain".to_owned())
        .spawn(move || event_loop(events_receiver, session_events_tx))
        .expect("failed to spawn alvr_oxr_event_drain thread");

    *SERVER_CORE_CONTEXT.write() = Some(context);
    *SESSION_EVENTS_RX.lock() = Some(session_events_rx);
    *EVENT_THREAD.lock() = Some(drain_thread);

    info!("alvr_oxr_init: OpenXR mode bridge ready (root_dir={root_dir:?})");
    AlvrOxrResult::Ok
}

/// Shut down the OpenXR-mode bridge. Called once by the Monado-side ALVR
/// driver at process exit.
///
/// # Safety
/// Must be called after the last bridge call has returned.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_shutdown() {
    // Signal the drain thread to exit, then drop the context (which drops
    // the events_sender — the thread's recv will return Disconnected if
    // the timeout poll hadn't already exited it via SHUTDOWN_FLAG).
    SHUTDOWN_FLAG.store(true, Ordering::Release);

    if SERVER_CORE_CONTEXT.write().take().is_none() {
        warn!("alvr_oxr_shutdown: not initialised; ignoring");
        return;
    }

    if let Some(join) = EVENT_THREAD.lock().take()
        && let Err(err) = join.join()
    {
        error!("alvr_oxr_shutdown: drain thread panicked: {err:?}");
    }
    SESSION_EVENTS_RX.lock().take();

    info!("alvr_oxr_shutdown: OpenXR mode bridge torn down");
}

/// Fill `out_serial` with the HMD's serial string. `buf_len` is the caller's
/// buffer size; the bridge writes at most `buf_len - 1` bytes plus a NUL.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_hmd_info(
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    // Phase 3.1.3 returns a stable bridge-specific serial. The OpenVR mode
    // maps this through HeadsetEmulationMode (props.rs:118) to mimic
    // Quest/Vive/etc. serials for SteamVR consumers; Monado generally
    // doesn't pin behaviour off the serial string the way SteamVR does, so
    // a single "ALVR_HMD" is sufficient for the runtime. A 3.1.5 follow-up
    // could thread HeadsetEmulationMode through if a downstream tool needs
    // the spoofed serials.
    write_c_string(out_serial, buf_len, "ALVR_HMD")
}

/// Fill `out_serial` with the controller's serial string. See
/// [`alvr_oxr_get_hmd_info`] for the buffer contract.
///
/// # Safety
/// `out_serial` must be a writable buffer of at least `buf_len` bytes, and
/// `buf_len >= 1`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_info(
    side: AlvrOxrSide,
    out_serial: *mut c_char,
    buf_len: usize,
) -> AlvrOxrResult {
    let serial = match side {
        AlvrOxrSide::Left => "ALVR_Controller_Left",
        AlvrOxrSide::Right => "ALVR_Controller_Right",
    };
    write_c_string(out_serial, buf_len, serial)
}

/// Pose returned by the bridge. Coordinate convention follows OpenXR
/// (right-handed, +Y up, -Z forward).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrPose {
    pub position: [f32; 3],
    pub orientation: [f32; 4], // (x, y, z, w)
}

// Default to identity, NOT zeroes. Quaternion (0,0,0,0) is degenerate — Monado's
// xrLocateViews path runs the chain-resolved result through
// `math_quat_ensure_normalized` and returns XR_ERROR_RUNTIME_FAILURE on a
// non-unit quat. The derived Default would emit (0,0,0,0) and surface as a
// silent runtime failure the moment any bridge getter falls back to it (e.g.
// `alvr_oxr_get_head_pose` before the client has reported a tracking sample).
impl Default for AlvrOxrPose {
    fn default() -> Self {
        Self {
            position: [0.0, 0.0, 0.0],
            orientation: [0.0, 0.0, 0.0, 1.0],
        }
    }
}

/// Query the predicted head pose at `at_timestamp_ns` (CLOCK_MONOTONIC ns).
///
/// # Safety
/// `out_pose` must be a writable `AlvrOxrPose`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_head_pose(
    at_timestamp_ns: i64,
    out_pose: *mut AlvrOxrPose,
) -> AlvrOxrResult {
    if out_pose.is_null() {
        return AlvrOxrResult::Failed;
    }
    unsafe { *out_pose = AlvrOxrPose::default() };

    let target = Duration::from_nanos(at_timestamp_ns.max(0) as u64);

    let Some(context) = &*SERVER_CORE_CONTEXT.read() else {
        return AlvrOxrResult::NotInitialised;
    };

    // get_device_motion returns the latest received tracking sample at or
    // before the requested timestamp. Phase 3.1.2 mirrors the OpenVR
    // pattern (server_openvr/src/lib.rs L96-L116) sans the explicit
    // predict() step — Monado already gives us a future predicted
    // timestamp, and an internal predict layer would require us to know
    // the source poll_timestamp. If timing accuracy turns out to need it,
    // a 3.1.5 follow-up can wire `motion.predict(now, target)` in.
    if let Some(motion) = context.get_device_motion(*HEAD_ID, target) {
        unsafe {
            *out_pose = AlvrOxrPose {
                position: motion.pose.position.to_array(),
                orientation: motion.pose.orientation.to_array(),
            };
        }
    }
    // No tracking yet (client hasn't connected, headset hasn't sent a
    // sample, etc.) → identity is fine; Monado treats Ok+identity as
    // "device present but uninitialised". Returning NotInitialised here
    // would make Monado disable the device.
    AlvrOxrResult::Ok
}

// `AlvrOxrControllerState::buttons` bitfield. Both sides share the same
// bit positions — left/right is implied by which controller's state you
// query. Trackpad / back-click / sensor sub-paths intentionally absent;
// add new bits at the next free position rather than reusing.
pub const ALVR_OXR_BUTTON_A_CLICK: u32 = 1 << 0;
pub const ALVR_OXR_BUTTON_A_TOUCH: u32 = 1 << 1;
pub const ALVR_OXR_BUTTON_B_CLICK: u32 = 1 << 2;
pub const ALVR_OXR_BUTTON_B_TOUCH: u32 = 1 << 3;
pub const ALVR_OXR_BUTTON_X_CLICK: u32 = 1 << 4;
pub const ALVR_OXR_BUTTON_X_TOUCH: u32 = 1 << 5;
pub const ALVR_OXR_BUTTON_Y_CLICK: u32 = 1 << 6;
pub const ALVR_OXR_BUTTON_Y_TOUCH: u32 = 1 << 7;
pub const ALVR_OXR_BUTTON_MENU_CLICK: u32 = 1 << 8;
pub const ALVR_OXR_BUTTON_SYSTEM_CLICK: u32 = 1 << 9;
pub const ALVR_OXR_BUTTON_THUMBSTICK_CLICK: u32 = 1 << 10;
pub const ALVR_OXR_BUTTON_THUMBSTICK_TOUCH: u32 = 1 << 11;
pub const ALVR_OXR_BUTTON_TRIGGER_CLICK: u32 = 1 << 12;
pub const ALVR_OXR_BUTTON_TRIGGER_TOUCH: u32 = 1 << 13;
pub const ALVR_OXR_BUTTON_SQUEEZE_CLICK: u32 = 1 << 14;
pub const ALVR_OXR_BUTTON_THUMBREST_TOUCH: u32 = 1 << 15;

// Device-kind discriminant for [`AlvrOxrEvent`] payloads that carry a per-device
// value (currently [`AlvrOxrEventType::Battery`]). `ServerCoreEvent::Battery`
// reports a `device_id: u64` hash; the bridge ABI can only fit `[i32; 4]`, so
// `device_id` is mapped to one of these small codes via [`device_kind_for`].
// Unknown devices (`Other`) are dropped before being pushed onto the queue —
// the Monado-side driver has no use for raw `u64` hashes here.
pub const ALVR_OXR_DEVICE_KIND_OTHER: i32 = 0;
pub const ALVR_OXR_DEVICE_KIND_HMD: i32 = 1;
pub const ALVR_OXR_DEVICE_KIND_LEFT_CONTROLLER: i32 = 2;
pub const ALVR_OXR_DEVICE_KIND_RIGHT_CONTROLLER: i32 = 3;

/// Resolution of the basis-points gauge encoding in [`encode_battery`]:
/// `gauge_value ∈ [0.0, 1.0]` becomes `0..=ALVR_OXR_BATTERY_GAUGE_SCALE`.
/// 10000 gives 0.01% resolution, plenty for a battery percent indicator.
pub const ALVR_OXR_BATTERY_GAUGE_SCALE: i32 = 10_000;

/// Map a tracking-system `device_id` (hashed path from `alvr_common`) to the
/// `ALVR_OXR_DEVICE_KIND_*` discriminant used in the bridge ABI. Returns
/// [`ALVR_OXR_DEVICE_KIND_OTHER`] for IDs the bridge doesn't expose.
fn device_kind_for(device_id: u64) -> i32 {
    if device_id == *HEAD_ID {
        ALVR_OXR_DEVICE_KIND_HMD
    } else if device_id == *HAND_LEFT_ID {
        ALVR_OXR_DEVICE_KIND_LEFT_CONTROLLER
    } else if device_id == *HAND_RIGHT_ID {
        ALVR_OXR_DEVICE_KIND_RIGHT_CONTROLLER
    } else {
        ALVR_OXR_DEVICE_KIND_OTHER
    }
}

/// Pack a `BatteryInfo` into the `[i32; 4]` payload of an `AlvrOxrEvent::Battery`:
///   data[0] = device-kind discriminant (see `ALVR_OXR_DEVICE_KIND_*`)
///   data[1] = gauge in basis points (0..=`ALVR_OXR_BATTERY_GAUGE_SCALE`)
///   data[2] = plugged flag (0 or 1)
///   data[3] = reserved (always 0)
/// Returns `None` for devices not exposed by the bridge — the drain thread
/// should drop the event in that case rather than emitting `Other`.
fn encode_battery(info: &BatteryInfo) -> Option<[i32; 4]> {
    let kind = device_kind_for(info.device_id);
    if kind == ALVR_OXR_DEVICE_KIND_OTHER {
        return None;
    }
    let gauge = (info.gauge_value.clamp(0.0, 1.0) * ALVR_OXR_BATTERY_GAUGE_SCALE as f32) as i32;
    Some([kind, gauge, info.is_plugged as i32, 0])
}

/// Per-view static parameters: the eye-to-head pose offset and the
/// per-view field of view, both in OpenXR conventions (radians for FOV,
/// right-handed +Y up -Z forward for the pose). `fov_radians` is
/// `[left, right, up, down]` to match [`AlvrOxrLayer::fov_radians`].
///
/// These come from the client's reported view configuration and arrive
/// on `ServerCoreEvent::LocalViewParams`. The bridge caches them in a
/// global so [`alvr_oxr_get_view_params`] can return them synchronously
/// — Monado's `xrLocateViews` equivalent calls into us once per frame
/// and shouldn't block on the connection thread.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrViewParams {
    pub pose: AlvrOxrPose,
    pub fov_radians: [f32; 4],
}

/// Read the cached view parameters for `side` (Left = view 0, Right = view 1).
/// Returns Ok with the latest cached params; before the client has reported
/// its view configuration the returned values reflect `ViewParams::DUMMY`
/// (identity pose + ±1 rad fov) so Monado doesn't trip on uninitialised
/// memory.
///
/// # Safety
/// `out_params` must be a writable `AlvrOxrViewParams`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_view_params(
    side: AlvrOxrSide,
    out_params: *mut AlvrOxrViewParams,
) -> AlvrOxrResult {
    if out_params.is_null() {
        return AlvrOxrResult::Failed;
    }
    let params = LOCAL_VIEW_PARAMS.read()[side as usize];
    unsafe {
        *out_params = AlvrOxrViewParams {
            pose: AlvrOxrPose {
                position: params.pose.position.to_array(),
                orientation: params.pose.orientation.to_array(),
            },
            fov_radians: [
                params.fov.left,
                params.fov.right,
                params.fov.up,
                params.fov.down,
            ],
        };
    }
    AlvrOxrResult::Ok
}

/// Per-frame controller state passed back over the bridge. Buttons and
/// analogue values mirror the OpenXR Touch profile layout.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrControllerState {
    pub pose: AlvrOxrPose,
    pub linear_velocity: [f32; 3],
    pub angular_velocity: [f32; 3],
    pub trigger: f32,
    pub squeeze: f32,
    pub thumbstick: [f32; 2],
    pub buttons: u32, // bitfield, see ALVR_OXR_BUTTON_*
}

/// Query the controller state at `at_timestamp_ns`.
///
/// # Safety
/// `out_state` must be a writable `AlvrOxrControllerState`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_controller_state(
    side: AlvrOxrSide,
    at_timestamp_ns: i64,
    out_state: *mut AlvrOxrControllerState,
) -> AlvrOxrResult {
    if out_state.is_null() {
        return AlvrOxrResult::Failed;
    }
    unsafe { *out_state = AlvrOxrControllerState::default() };

    let target = Duration::from_nanos(at_timestamp_ns.max(0) as u64);

    let Some(context) = &*SERVER_CORE_CONTEXT.read() else {
        return AlvrOxrResult::NotInitialised;
    };

    if let Some(motion) = context.get_device_motion(side_device_id(side), target) {
        unsafe {
            (*out_state).pose = AlvrOxrPose {
                position: motion.pose.position.to_array(),
                orientation: motion.pose.orientation.to_array(),
            };
            (*out_state).linear_velocity = motion.linear_velocity.to_array();
            (*out_state).angular_velocity = motion.angular_velocity.to_array();
        }
    }

    // Analogue + button bitfield from the cache maintained by the drain
    // thread on ServerCoreEvent::Buttons. The cache slot index matches
    // AlvrOxrSide's discriminant (Left = 0, Right = 1).
    let cache = CONTROLLER_BUTTON_CACHE.lock();
    let slot = &cache[side as usize];
    unsafe {
        (*out_state).trigger = slot.trigger;
        (*out_state).squeeze = slot.squeeze;
        (*out_state).thumbstick = slot.thumbstick;
        (*out_state).buttons = slot.buttons;
    }

    AlvrOxrResult::Ok
}

/// Haptic pulse parameters. Maps onto OpenXR `XrHapticVibration`.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrHaptic {
    pub duration_ns: i64,
    pub frequency_hz: f32,
    pub amplitude: f32,
}

/// Trigger a haptic pulse on the given controller.
///
/// # Safety
/// `params` must point to a valid `AlvrOxrHaptic`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_set_haptic(
    side: AlvrOxrSide,
    params: *const AlvrOxrHaptic,
) -> AlvrOxrResult {
    if params.is_null() {
        return AlvrOxrResult::Failed;
    }
    let params = unsafe { *params };

    let Some(context) = &*SERVER_CORE_CONTEXT.read() else {
        return AlvrOxrResult::NotInitialised;
    };

    context.send_haptics(Haptics {
        device_id: side_device_id(side),
        duration: Duration::from_nanos(params.duration_ns.max(0) as u64),
        frequency: params.frequency_hz,
        amplitude: params.amplitude,
    });

    AlvrOxrResult::Ok
}

/// Per-joint pose payload returned by [`alvr_oxr_get_hand_skeleton`]. Joints
/// are indexed by the `XR_HAND_JOINT_*_EXT` order, which matches Monado's
/// `xrt_hand_joint` enum 1:1 (`XRT_HAND_JOINT_PALM .. XRT_HAND_JOINT_LITTLE_TIP`).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct AlvrOxrHandJoint {
    pub pose: AlvrOxrPose,
}

/// Number of joints per hand in the OpenXR `XR_EXT_hand_tracking` skeleton.
/// Matches `XR_HAND_JOINT_COUNT_EXT` and the length of
/// `TrackingData::hand_skeletons[side]`.
pub const ALVR_OXR_HAND_JOINT_COUNT: u32 = 26;

/// Query the predicted hand skeleton at `at_timestamp_ns`. Writes
/// `ALVR_OXR_HAND_JOINT_COUNT` joints into `out_joints` when the client has a
/// tracked hand on this side. Sets `*out_is_tracked = false` and leaves
/// `out_joints` untouched when the client reports `hand_skeletons[side] = None`
/// for the resolved frame.
///
/// Sources the skeleton from `ServerCoreContext::get_hand_skeleton`, which
/// **ignores `at_timestamp_ns`** and returns the most recently received
/// `TrackingData.hand_skeletons[side]` sample. Quest hand samples are
/// timestamped in the client's predicted-display clock domain and there is no
/// client↔server time sync, so timestamp-based matching cannot align with the
/// PC-runtime clock that OpenXR callers query in. Staleness is bounded by the
/// Quest's send cadence (~10–16 ms). Joint order matches the
/// `XR_HAND_JOINT_*_EXT` enum 1:1 — the bridge does no reordering, so the
/// Monado-side `xrt_device::get_hand_tracking` can hand them straight to the
/// state tracker. Returns `NotInitialised` when the bridge isn't initialised;
/// otherwise `Ok` with `is_tracked` indicating whether real data was written.
///
/// # Safety
/// `out_joints` must be a writable buffer of at least
/// `ALVR_OXR_HAND_JOINT_COUNT` elements. `out_is_tracked` must be writable.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_hand_skeleton(
    side: AlvrOxrSide,
    at_timestamp_ns: i64,
    out_joints: *mut AlvrOxrHandJoint,
    out_is_tracked: *mut bool,
) -> AlvrOxrResult {
    if out_joints.is_null() || out_is_tracked.is_null() {
        return AlvrOxrResult::Failed;
    }
    // Default to "no tracking"; out_joints stays untouched in that case so a
    // caller that ignores out_is_tracked still sees its zero-initialised
    // buffer rather than stale data from a different frame.
    unsafe { *out_is_tracked = false };

    let target = Duration::from_nanos(at_timestamp_ns.max(0) as u64);
    let hand_type = match side {
        AlvrOxrSide::Left => HandType::Left,
        AlvrOxrSide::Right => HandType::Right,
    };

    let Some(context) = &*SERVER_CORE_CONTEXT.read() else {
        return AlvrOxrResult::NotInitialised;
    };

    if let Some(skeleton) = context.get_hand_skeleton(hand_type, target) {
        for (i, joint_pose) in skeleton.iter().enumerate() {
            unsafe {
                *out_joints.add(i) = AlvrOxrHandJoint {
                    pose: AlvrOxrPose {
                        position: joint_pose.position.to_array(),
                        orientation: joint_pose.orientation.to_array(),
                    },
                };
            }
        }
        unsafe { *out_is_tracked = true };
    }

    AlvrOxrResult::Ok
}

/// Per-view foveation parameters. Lengths in image-space [0, 1]; centre at
/// (0.5, 0.5) when shifts are zero. `edge_ratio[*]` are the per-axis fall-off
/// factors (matches `alvr_session::FoveatedEncodingConfig`). Set
/// `is_present = false` to mean "no foveation for this view this frame —
/// encode the whole half at full resolution" (useful when an eye loses
/// tracking confidence, or when foveation is disabled session-wide).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrFoveationView {
    pub is_present: bool,
    pub center_size: [f32; 2],
    pub center_shift: [f32; 2],
    pub edge_ratio: [f32; 2],
}

/// Cache default — "no foveation for this view". `edge_ratio` is 1.0 (no
/// fall-off) rather than 0.0 so a caller that ignores `is_present` still
/// behaves sensibly (matches `FoveatedEncodingConfig`'s valid range
/// `[1.0, 10.0]`).
const DEFAULT_FOVEATION_VIEW: AlvrOxrFoveationView = AlvrOxrFoveationView {
    is_present: false,
    center_size: [0.0; 2],
    center_shift: [0.0; 2],
    edge_ratio: [1.0; 2],
};

/// Bridge-side cache of the latest per-view foveation params. Written by
/// [`alvr_oxr_set_foveation`] (driven by the drain thread when the future
/// `ServerCoreEvent::PerViewFoveation` lands), read synchronously from the
/// encoder via [`alvr_oxr_get_foveation`]. Defaults to no-foveation on both
/// sides so the encoder defaults to full-resolution before any update lands.
///
/// Lives outside [`SERVER_CORE_CONTEXT`] on purpose: foveation is config-shaped
/// (it survives connect/disconnect cycles cleanly) and the encoder hot-path
/// shouldn't pay the cost of a SERVER_CORE_CONTEXT read just to ask for it.
static FOVEATION: RwLock<[AlvrOxrFoveationView; 2]> = RwLock::new([DEFAULT_FOVEATION_VIEW; 2]);

/// Build a bridge-shape [`AlvrOxrFoveationView`] from server_core's
/// [`PerViewFoveationView`]. The producing side has no notion of "absent" —
/// any event delivered means we have valid params for this view, so
/// `is_present = true`.
fn per_view_to_bridge(view: &PerViewFoveationView) -> AlvrOxrFoveationView {
    AlvrOxrFoveationView {
        is_present: true,
        center_size: view.center_size,
        center_shift: view.center_shift,
        edge_ratio: view.edge_ratio,
    }
}

/// Read the latest cached per-view foveation params. Drives the encoder side
/// inside [`alvr_oxr_submit_layers`]. Returns `Ok` with `is_present = false`
/// for both views when foveation is disabled session-wide or no update has
/// landed yet; the encoder should encode at full resolution in that case.
///
/// # Safety
/// `out_views` must be a writable buffer of 2 [`AlvrOxrFoveationView`]s
/// (left = index 0, right = index 1).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_foveation(
    out_views: *mut AlvrOxrFoveationView,
) -> AlvrOxrResult {
    if out_views.is_null() {
        return AlvrOxrResult::Failed;
    }
    let state = *FOVEATION.read();
    unsafe {
        *out_views = state[0];
        *out_views.add(1) = state[1];
    }
    AlvrOxrResult::Ok
}

/// Push a new per-view foveation update into the bridge. Called by the
/// `server_core` drain thread when a new `ServerCoreEvent::PerViewFoveation`
/// arrives (which itself is fed by either an eye-tracking → foveation-centre
/// worker or a future `RealTimeConfig.per_view_foveation` field).
///
/// # Safety
/// `views` must point to 2 [`AlvrOxrFoveationView`]s. Caller retains ownership;
/// the bridge copies into its internal cache.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_set_foveation(
    views: *const AlvrOxrFoveationView,
) -> AlvrOxrResult {
    if views.is_null() {
        return AlvrOxrResult::Failed;
    }
    let new_state = unsafe { [*views, *views.add(1)] };
    *FOVEATION.write() = new_state;
    AlvrOxrResult::Ok
}

/// Static foveated-encoding compress parameters for the encoder's FFR pass.
/// Unlike the per-frame [`AlvrOxrFoveationView`] cache (gaze-driven centre
/// shift), these are derived once from the negotiated session config and tell
/// `comp_alvr` how to set up its `ffr.comp` compute pass: the foveated output
/// resolution and the eight specialization constants the shader consumes.
///
/// When `enabled` is `false`, foveated encoding is off session-wide; the
/// encoder should skip the FFR pass and encode the full-resolution image
/// (`optimized_*` then equal the full per-eye resolution and the ratios are
/// identity).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrFoveationVars {
    /// `false` => foveated encoding disabled; encode full-res, skip FFR.
    pub is_enabled: bool,
    /// 32-aligned foveated per-eye width (`ffr.comp` output). Combined frame
    /// width is `2 * optimized_width`.
    pub optimized_width: u32,
    /// 32-aligned foveated per-eye height (`ffr.comp` output).
    pub optimized_height: u32,
    /// `eyeSizeRatio` spec constant (`VIEW_WIDTH/HEIGHT_RATIO` on the client).
    pub eye_size_ratio: [f32; 2],
    /// `centerSize` spec constant (aligned).
    pub center_size: [f32; 2],
    /// `centerShift` spec constant (aligned).
    pub center_shift: [f32; 2],
    /// `edgeRatio` spec constant (raw, per axis).
    pub edge_ratio: [f32; 2],
}

/// Read the static foveated-encoding compress parameters derived from the
/// negotiated `openvr_config`. Called once by the Monado-side `comp_alvr` when
/// it builds the FFR compute pass (and again on reconnect, since the
/// negotiated resolution / foveation config can change between sessions).
///
/// Mirrors the resolution math [`alvr_oxr_get_view_resolution`] reports: the
/// app still renders / the squasher still composes at the *full* per-eye
/// resolution; this FFR pass then compresses that down to `optimized_*`, which
/// is what the encoder sizes to and the client de-foveates back up from.
///
/// # Safety
/// `out_vars` must point to a writable [`AlvrOxrFoveationVars`].
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_get_foveation_vars(
    out_vars: *mut AlvrOxrFoveationVars,
) -> AlvrOxrResult {
    if out_vars.is_null() {
        return AlvrOxrResult::Failed;
    }

    let oc = alvr_server_core::openvr_config();

    let vars = if oc.enable_foveated_encoding {
        let config = FoveatedEncodingConfig {
            force_enable: false,
            center_size_x: oc.foveation_center_size_x,
            center_size_y: oc.foveation_center_size_y,
            center_shift_x: oc.foveation_center_shift_x,
            center_shift_y: oc.foveation_center_shift_y,
            edge_ratio_x: oc.foveation_edge_ratio_x,
            edge_ratio_y: oc.foveation_edge_ratio_y,
            // The per-frame gaze-driven shift flows through the separate
            // [`alvr_oxr_get_foveation`] cache; this static derivation uses the
            // session-config centre only.
            per_view_eye_tracked: Switch::Disabled,
        };
        let compress = foveation_compress_vars(
            UVec2::new(oc.eye_resolution_width, oc.eye_resolution_height),
            config,
        );
        AlvrOxrFoveationVars {
            is_enabled: true,
            optimized_width: compress.optimized_view_resolution.x,
            optimized_height: compress.optimized_view_resolution.y,
            eye_size_ratio: compress.eye_size_ratio,
            center_size: compress.center_size,
            center_shift: compress.center_shift,
            edge_ratio: compress.edge_ratio,
        }
    } else {
        // Foveation off: encode at full resolution, identity ratios.
        AlvrOxrFoveationVars {
            is_enabled: false,
            optimized_width: oc.eye_resolution_width,
            optimized_height: oc.eye_resolution_height,
            eye_size_ratio: [1.0, 1.0],
            center_size: [0.0, 0.0],
            center_shift: [0.0, 0.0],
            edge_ratio: [1.0, 1.0],
        }
    };

    // # Safety: caller guarantees `out_vars` is writable.
    unsafe { *out_vars = vars };
    AlvrOxrResult::Ok
}

/// One submitted OpenXR composition layer. The Monado-side compositor builds
/// an array of these and hands them to the bridge once per frame.
///
/// Image handles are platform-specific:
/// * Windows: `HANDLE` from a `D3D11_RESOURCE_MISC_SHARED_NTHANDLE` resource
///   or `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32` (`u64` of the HANDLE).
/// * Linux: DMABUF fd (cast to `u64`).
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrLayer {
    pub layer_type: u32,           // see XRT_LAYER_*
    pub view_count: u32,
    pub image_handles: [u64; 2],   // left/right view, native handles
    pub image_sizes: [u64; 2], // left/right backing allocation size in bytes (v6)
    pub width: u32,
    pub height: u32,
    pub fov_radians: [f32; 4],     // per view: [left, right, up, down]; primary view only
    pub pose: AlvrOxrPose,
}

/// OpenXR-mode NVENC encoder bridge (Slice 3.3c). Wraps the C++ `VkEncoderBackend`
/// (`cpp/encoder/win32_vk/`, exposed via `VkEncoderBackendC.h`): created on
/// `ClientConnected` from the negotiated `openvr_config`, fed by
/// [`alvr_oxr_submit_layers`], output NALs pushed back through `server_core`
/// (`send_video_nal` / `set_video_config_nals`) — the OpenXR counterpart to
/// `alvr_server_openvr`'s `VideoSend` path.
///
/// Windows-only: the encoder C++ is compiled only on Windows (see
/// `server_openxr/build.rs`), so other targets get the no-op stubs that keep the
/// crate building cross-platform.
#[cfg(target_os = "windows")]
mod encoder_bridge {
    use super::{AlvrOxrLayer, HEAD_ID, LOCAL_VIEW_PARAMS, SERVER_CORE_CONTEXT};
    use alvr_common::{ViewParams, warn};
    use alvr_session::{CodecType, OpenvrConfig};
    use std::{
        ffi::{CStr, c_char, c_void},
        ptr, slice,
        time::Duration,
    };

    // #[repr(C)] mirror of the C++ NvencConfig (encoder/NvencConfig.h). Field
    // order and types MUST stay identical: repr(C) and the C++ default struct
    // layout follow the same rules, so matching fields => matching bytes.
    #[repr(C)]
    struct VkNvencConfig {
        codec: i32,
        refresh_rate: i32,
        render_width: i32,
        render_height: i32,
        bitrate_bps: u64,
        enable_hdr: bool,
        use_10bit_encoder: bool,
        nvenc_quality_preset: u32,
        nvenc_tuning_preset: u32,
        nvenc_refresh_rate: i64,
        nvenc_enable_weighted_prediction: bool,
        nvenc_max_num_ref_frames: i64,
        nvenc_gop_length: i64,
        entropy_coding: u32,
        nvenc_enable_intra_refresh: bool,
        nvenc_intra_refresh_period: i64,
        nvenc_intra_refresh_count: i64,
        filler_data: bool,
        rate_control_mode: u32,
        nvenc_p_frame_strategy: i64,
        nvenc_multi_pass: u32,
        nvenc_low_delay_key_frame_scale: i64,
        nvenc_adaptive_quantization_mode: u32,
        nvenc_rate_control_mode: i64,
        nvenc_rc_buffer_size: i64,
        nvenc_rc_initial_delay: i64,
        nvenc_rc_max_bitrate: i64,
        nvenc_rc_average_bitrate: i64,
    }

    // #[repr(C)] mirror of AlvrVkSubmitDesc (VkEncoderBackendC.h).
    #[repr(C)]
    struct VkSubmitDesc {
        image_handle_left: u64,
        image_handle_right: u64,
        image_size_left: u64,
        image_size_right: u64,
        image_format: u32,
        image_width: u32,
        image_height: u32,
        sync_semaphore_handle: u64,
        sync_semaphore_value: u64,
        presentation_time_ns: u64,
        target_timestamp_ns: u64,
    }

    type VkPacketCallback = unsafe extern "C" fn(*mut c_void, *const u8, i32, bool, u64);

    unsafe extern "C" {
        fn alvr_vk_encoder_last_error() -> *const c_char;
        fn alvr_vk_encoder_submit_diag() -> *const c_char;
        fn alvr_vk_encoder_create(cfg: *const VkNvencConfig) -> *mut c_void;
        fn alvr_vk_encoder_destroy(handle: *mut c_void);
        fn alvr_vk_encoder_on_stream_start(handle: *mut c_void);
        fn alvr_vk_encoder_get_seq_params(handle: *mut c_void, out_buf: *mut u8, cap: i32) -> i32;
        fn alvr_vk_encoder_submit(
            handle: *mut c_void,
            desc: *const VkSubmitDesc,
            cb: VkPacketCallback,
            ctx: *mut c_void,
        ) -> bool;
    }

    // The encoder handle (VkEncoderBackend*) created on the drain thread and read
    // by alvr_oxr_submit_layers on the compositor thread. The lock is held across
    // a submit so a concurrent disconnect can't destroy it mid-encode; the C++
    // side makes its own CUDA context current per call, so cross-thread use is
    // fine. # Safety: the pointer is only ever produced by alvr_vk_encoder_create
    // and destroyed once.
    struct Handle(*mut c_void);
    unsafe impl Send for Handle {}
    static ENCODER: alvr_common::parking_lot::Mutex<Option<Handle>> =
        alvr_common::parking_lot::Mutex::new(None);

    fn codec_type(codec: u8) -> CodecType {
        match codec {
            1 => CodecType::Hevc,
            2 => CodecType::AV1,
            _ => CodecType::H264,
        }
    }

    fn build_config(oc: &OpenvrConfig) -> VkNvencConfig {
        // Default base bitrate matches the OpenVR NVENC path's 30 Mbit seed; the
        // negotiated rc_average_bitrate overrides it when set.
        let bitrate_bps = if oc.rc_average_bitrate > 0 {
            oc.rc_average_bitrate as u64
        } else {
            30_000_000
        };
        VkNvencConfig {
            codec: oc.codec as i32,
            refresh_rate: oc.refresh_rate as i32,
            // Both eyes are packed side by side into one encoded frame.
            render_width: (oc.eye_resolution_width * 2) as i32,
            render_height: oc.eye_resolution_height as i32,
            bitrate_bps,
            enable_hdr: oc.enable_hdr,
            use_10bit_encoder: oc.use_10bit_encoder,
            nvenc_quality_preset: oc.nvenc_quality_preset,
            nvenc_tuning_preset: oc.nvenc_tuning_preset,
            nvenc_refresh_rate: oc.nvenc_refresh_rate,
            nvenc_enable_weighted_prediction: oc.nvenc_enable_weighted_prediction,
            nvenc_max_num_ref_frames: oc.max_num_ref_frames,
            nvenc_gop_length: oc.gop_length,
            entropy_coding: oc.entropy_coding,
            nvenc_enable_intra_refresh: oc.enable_intra_refresh,
            nvenc_intra_refresh_period: oc.intra_refresh_period,
            nvenc_intra_refresh_count: oc.intra_refresh_count,
            filler_data: oc.filler_data,
            rate_control_mode: oc.rate_control_mode,
            nvenc_p_frame_strategy: oc.p_frame_strategy,
            nvenc_multi_pass: oc.nvenc_multi_pass,
            nvenc_low_delay_key_frame_scale: oc.nvenc_low_delay_key_frame_scale,
            nvenc_adaptive_quantization_mode: oc.nvenc_adaptive_quantization_mode,
            nvenc_rate_control_mode: oc.nvenc_rate_control_mode,
            nvenc_rc_buffer_size: oc.rc_buffer_size,
            nvenc_rc_initial_delay: oc.rc_initial_delay,
            nvenc_rc_max_bitrate: oc.rc_max_bitrate,
            nvenc_rc_average_bitrate: oc.rc_average_bitrate,
        }
    }

    // NVENC output sink. Forwards each NAL to server_core with the latest cached
    // view params (the client matches the frame to a pose by these + timestamp).
    unsafe extern "C" fn on_packet(
        _ctx: *mut c_void,
        data: *const u8,
        len: i32,
        is_idr: bool,
        target_timestamp_ns: u64,
    ) {
        if data.is_null() || len <= 0 {
            return;
        }
        // # Safety: NVENC guarantees `len` valid bytes for the call's duration.
        let nal = unsafe { slice::from_raw_parts(data, len as usize) }.to_vec();

        // Diagnostic: log the first several encoded NALs (byte length + the first
        // bytes, which carry the HEVC start code + NAL-unit type) to confirm
        // NVENC is producing a real bitstream and the headers look sane.
        {
            use std::sync::atomic::{AtomicU32, Ordering};
            static NAL_LOG: AtomicU32 = AtomicU32::new(0);
            if NAL_LOG.fetch_add(1, Ordering::Relaxed) < 10 {
                let head = &nal[..nal.len().min(8)];
                warn!(
                    "OpenXR NAL: len={} is_idr={} head={head:02x?}",
                    nal.len(),
                    is_idr
                );
            }
        }

        if let Some(ctx) = SERVER_CORE_CONTEXT.read().as_ref() {
            // The client reprojects the decoded frame using these per-eye view
            // params, so they must be GLOBAL (world-space): head_pose × the
            // head-relative LOCAL_VIEW_PARAMS — mirroring alvr_server_openvr's
            // send_video. Passing the local (head-relative) params directly
            // anchors the frame at the origin, so the client reprojects it far
            // off the current head pose → off-screen → black.
            let local = *LOCAL_VIEW_PARAMS.read();
            let stamp = Duration::from_nanos(target_timestamp_ns);
            let global_view_params = match ctx.get_device_motion(*HEAD_ID, stamp) {
                Some(head) => [
                    ViewParams {
                        pose: head.pose * local[0].pose,
                        fov: local[0].fov,
                    },
                    ViewParams {
                        pose: head.pose * local[1].pose,
                        fov: local[1].fov,
                    },
                ],
                None => local,
            };
            ctx.send_video_nal(stamp, global_view_params, is_idr, nal);
        }
    }

    pub fn start() {
        let oc = alvr_server_core::openvr_config();
        let cfg = build_config(&oc);
        // # Safety: `cfg` outlives the call; Create copies what it needs.
        let handle = unsafe { alvr_vk_encoder_create(&cfg) };
        if handle.is_null() {
            // # Safety: the C side returns a valid NUL-terminated static/global
            // string, never null.
            let reason = unsafe { CStr::from_ptr(alvr_vk_encoder_last_error()) }.to_string_lossy();
            warn!(
                "OpenXR mode: NVENC encoder unavailable; no video will stream. \
                 Encoder config: codec={} {}x{} @ {}Hz, {} bps. Reason: {reason}",
                cfg.codec, cfg.render_width, cfg.render_height, cfg.refresh_rate, cfg.bitrate_bps
            );
            return;
        }
        // # Safety: handle just came from create and is non-null.
        unsafe { alvr_vk_encoder_on_stream_start(handle) };

        // Publish sequence-header (SPS/PPS/VPS) NALs. Query the length first
        // (cap 0 = no copy), then fetch into a right-sized buffer.
        // # Safety: handle valid; null/0 means "just return the length".
        let len = unsafe { alvr_vk_encoder_get_seq_params(handle, ptr::null_mut(), 0) };
        if len > 0 {
            let mut buf = vec![0u8; len as usize];
            // # Safety: buf has `len` bytes of capacity.
            let written = unsafe { alvr_vk_encoder_get_seq_params(handle, buf.as_mut_ptr(), len) };
            buf.truncate(written.max(0) as usize);
            if let Some(ctx) = SERVER_CORE_CONTEXT.read().as_ref() {
                ctx.set_video_config_nals(buf, codec_type(oc.codec));
            }
        }

        *ENCODER.lock() = Some(Handle(handle));
    }

    pub fn stop() {
        if let Some(handle) = ENCODER.lock().take() {
            // # Safety: handle came from create and is destroyed exactly once.
            unsafe { alvr_vk_encoder_destroy(handle.0) };
        }
    }

    pub fn submit(layer: &AlvrOxrLayer, sync_handle: u64, monado_display_time_ns: u64) -> bool {
        let guard = ENCODER.lock();
        let Some(handle) = guard.as_ref() else {
            return false;
        };
        // Stamp the frame with the client's latest tracking poll_timestamp (its
        // own clock) so it can correlate the decoded frame to a pose it sent.
        // Monado's compositor display time is a different clock with no sync, so
        // the client matches nothing and discards every frame (black). Fall back
        // to the Monado time only before any tracking has arrived.
        let latest_poll =
            super::LATEST_POLL_TIMESTAMP_NS.load(std::sync::atomic::Ordering::Relaxed);
        let stamp_ns = if latest_poll != 0 {
            latest_poll
        } else {
            monado_display_time_ns
        };
        let desc = VkSubmitDesc {
            image_handle_left: layer.image_handles[0],
            image_handle_right: layer.image_handles[1],
            image_size_left: layer.image_sizes[0],
            image_size_right: layer.image_sizes[1],
            // image_format stays 0: comp_alvr's squasher output is RGBA8 and the
            // encoder assumes ABGR. A future ABI rev can carry the VkFormat if a
            // non-RGBA8 scratch format is ever introduced.
            image_format: 0,
            image_width: layer.width,
            image_height: layer.height,
            sync_semaphore_handle: sync_handle,
            sync_semaphore_value: 0,
            presentation_time_ns: 0,
            target_timestamp_ns: stamp_ns,
        };
        // # Safety: handle valid for the lock's duration; desc outlives the call;
        // on_packet is a valid extern "C" fn.
        let ok = unsafe { alvr_vk_encoder_submit(handle.0, &desc, on_packet, ptr::null_mut()) };

        // Log the GPU-read-back content sample for the first few frames so we can
        // tell whether the encoder is fed real pixels or zeros (black-frame
        // diagnosis). Throttled so it doesn't spam the per-frame log.
        use std::sync::atomic::{AtomicU32, Ordering};
        static DIAG_FRAMES: AtomicU32 = AtomicU32::new(0);
        if DIAG_FRAMES.fetch_add(1, Ordering::Relaxed) < 5 {
            // # Safety: returns a valid NUL-terminated global string, never null.
            let diag = unsafe { CStr::from_ptr(alvr_vk_encoder_submit_diag()) }.to_string_lossy();
            warn!("OpenXR encoder content diag: {diag}");
        }
        ok
    }
}

#[cfg(not(target_os = "windows"))]
mod encoder_bridge {
    use super::AlvrOxrLayer;

    pub fn start() {}
    pub fn stop() {}
    pub fn submit(_layer: &AlvrOxrLayer, _sync_handle: u64, _target_timestamp_ns: u64) -> bool {
        false
    }
}

/// Submit a frame's worth of composition layers.
///
/// Forwards the projection layer (`layers[0]`) to the NVENC encoder via
/// [`encoder_bridge`]; encoded NALs flow back through `server_core::send_video_nal`
/// from the encoder's packet callback. Non-projection layers are squashed into
/// the projection image by `comp_alvr` before this call, so only `layers[0]` is
/// read here.
///
/// Returns `Ok` when the frame was encoded, `Failed` when it was dropped (e.g.
/// the encoder isn't up or the external-memory import failed). Never
/// `NotImplemented` now that the body is wired.
///
/// `display_time_ns` is the frame's predicted display time (Monado-monotonic
/// nanoseconds); the encoded NALs carry it so the client can match the frame to
/// a tracking pose.
///
/// # Safety
/// `layers` must point to `layer_count` valid `AlvrOxrLayer`s. `sync_handle`
/// may be 0 to indicate "no GPU sync, use a fence".
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_submit_layers(
    frame_id: i64,
    layer_count: u32,
    layers: *const AlvrOxrLayer,
    sync_handle: u64,
    display_time_ns: i64,
) -> AlvrOxrResult {
    let _ = frame_id;
    if layers.is_null() || layer_count == 0 {
        return AlvrOxrResult::Failed;
    }

    // # Safety: caller guarantees `layers` points to `layer_count` valid layers;
    // we read only the first (the squashed projection layer).
    let layer = unsafe { &*layers };

    // Monado-monotonic ns; clamp the (always-positive) predicted display time
    // into the u64 the encoder/send_video_nal path uses.
    let target_timestamp_ns = display_time_ns.max(0) as u64;

    if encoder_bridge::submit(layer, sync_handle, target_timestamp_ns) {
        AlvrOxrResult::Ok
    } else {
        AlvrOxrResult::Failed
    }
}

/// Report per-frame compositor pacing timestamps for telemetry.
///
/// Called by the Monado-side `comp_alvr` after the `layer_commit` pacing
/// markers fire (matches `u_pc_mark_point` semantics):
/// - `begin_ns` — start of compositor work for this frame
///   (`U_TIMING_POINT_BEGIN`).
/// - `submit_begin_ns` — moment work is handed to the GPU/encoder, i.e.
///   just before [`alvr_oxr_submit_layers`] (`U_TIMING_POINT_SUBMIT_BEGIN`).
/// - `submit_end_ns` — moment the handoff completed
///   (`U_TIMING_POINT_SUBMIT_END`).
///
/// All timestamps are in nanoseconds from the same monotonic clock used by
/// `u_pacing` (`os_monotonic_get_ns()`). The bridge intentionally accepts
/// raw timestamps rather than pre-computed deltas so the Rust side can build
/// any window/aggregation shape it likes.
///
/// Forwards the sample into `alvr_server_core`'s metrics exporter via
/// [`ServerCoreContext::report_oxr_pacing`]. The metrics aggregator
/// derives CPU and submit durations and exports them in the standard
/// per-window snapshot under the `oxr_pacing` field. Drops silently when
/// no client is connected (no metrics sender wired up yet) or when the
/// bridge context is not initialised. Always returns `Ok` so the
/// compositor doesn't log a per-frame failure.
///
/// # Safety
/// Always safe to call. Takes only `Copy` POD values.
#[unsafe(no_mangle)]
pub extern "C" fn alvr_oxr_report_pacing(
    frame_id: i64,
    begin_ns: i64,
    submit_begin_ns: i64,
    submit_end_ns: i64,
) -> AlvrOxrResult {
    let _ = frame_id;
    if let Some(ctx) = SERVER_CORE_CONTEXT.read().as_ref() {
        ctx.report_oxr_pacing(begin_ns, submit_begin_ns, submit_end_ns);
    }
    AlvrOxrResult::Ok
}

/// Report per-frame counts of non-projection layers the compositor saw.
///
/// `comp_alvr` currently passes only `XRT_LAYER_PROJECTION` /
/// `XRT_LAYER_PROJECTION_DEPTH` layers to the encoder and drops everything
/// else. This entrypoint lets it report what was dropped so the metrics
/// exporter can surface "what kinds of overlays do real apps actually
/// submit" — a useful prior for Phase 7 rasterisation work (build quad
/// support first if most apps submit quads, etc.).
///
/// Each `n_*` count is the number of layers of that type on this single
/// frame. Frame-id is taken purely so future versions can correlate with
/// the pacing sample for the same frame; the current aggregator does not
/// retain it.
///
/// Always returns `Ok`. Drops silently when no client is connected.
///
/// # Safety
/// Always safe to call. Takes only `Copy` POD values.
#[unsafe(no_mangle)]
pub extern "C" fn alvr_oxr_report_layer_types(
    frame_id: i64,
    n_quad: u32,
    n_cylinder: u32,
    n_equirect: u32,
    n_cube: u32,
    n_passthrough: u32,
) -> AlvrOxrResult {
    let _ = frame_id;
    if let Some(ctx) = SERVER_CORE_CONTEXT.read().as_ref() {
        ctx.report_oxr_layer_types(n_quad, n_cylinder, n_equirect, n_cube, n_passthrough);
    }
    AlvrOxrResult::Ok
}

/// Session-event type discriminant. Mirrors `enum xrt_session_event_type`
/// loosely; trimmed down to what ALVR cares about.
#[repr(i32)]
#[derive(Clone, Copy, Debug)]
pub enum AlvrOxrEventType {
    None = 0,
    StateChange = 1,
    Battery = 2,
    ConnectionLost = 4,
    RefreshRateChange = 5,
}

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct AlvrOxrEvent {
    pub event_type: AlvrOxrEventType,
    pub timestamp_ns: i64,
    pub data: [i32; 4], // event-type-specific payload
}

/// Poll one session event from the bridge. Returns
/// [`AlvrOxrResult::Ok`] with `out_event.event_type == None` when the queue
/// is empty.
///
/// # Safety
/// `out_event` must be a writable `AlvrOxrEvent`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn alvr_oxr_poll_session_event(out_event: *mut AlvrOxrEvent) -> AlvrOxrResult {
    if out_event.is_null() {
        return AlvrOxrResult::Failed;
    }

    let mut event = AlvrOxrEvent {
        event_type: AlvrOxrEventType::None,
        timestamp_ns: 0,
        data: [0; 4],
    };

    if let Some(rx) = SESSION_EVENTS_RX.lock().as_ref()
        && let Ok(received) = rx.try_recv()
    {
        event = received;
    }

    unsafe { *out_event = event };
    AlvrOxrResult::Ok
}

#[cfg(test)]
mod tests {
    use super::*;

    // Squared L2 norm of an (x, y, z, w) quaternion. A unit quaternion is ~1.0.
    fn quat_norm_sq(q: [f32; 4]) -> f32 {
        q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3]
    }

    // Regression guard for the zero-quaternion bug (fix 1eac1daf): a (0,0,0,0)
    // orientation flowed out of `alvr_oxr_get_head_pose` before any client
    // connected, `alvr_hmd_get_tracked_pose` stamped ORIENTATION_VALID on it,
    // and Monado's xrLocateViews failed with XR_ERROR_RUNTIME_FAILURE in
    // `math_quat_ensure_normalized`. A derived Default would re-introduce it
    // silently — pin the identity here so that can't ship again.
    #[test]
    fn default_pose_orientation_is_identity() {
        let pose = AlvrOxrPose::default();
        assert_eq!(pose.orientation, [0.0, 0.0, 0.0, 1.0]);
        assert!(
            (quat_norm_sq(pose.orientation) - 1.0).abs() < 1e-6,
            "default orientation must be a unit quaternion, got {:?}",
            pose.orientation
        );
    }

    // Before a client reports its view config the bridge serves ViewParams::DUMMY.
    // The orientation it hands Monado must be normalizable for both eyes, or the
    // same xrLocateViews failure fires during session bring-up.
    #[test]
    fn dummy_view_params_orientation_is_normalized() {
        for side in [AlvrOxrSide::Left, AlvrOxrSide::Right] {
            let mut params = AlvrOxrViewParams {
                pose: AlvrOxrPose::default(),
                fov_radians: [0.0; 4],
            };
            let ret = unsafe { alvr_oxr_get_view_params(side, &mut params) };
            assert!(matches!(ret, AlvrOxrResult::Ok), "got {ret:?}");
            assert!(
                (quat_norm_sq(params.pose.orientation) - 1.0).abs() < 1e-6,
                "{side:?} dummy view orientation not normalized: {:?}",
                params.pose.orientation
            );
        }
    }

    // With no SERVER_CORE_CONTEXT (no client) the getter must still leave a
    // normalized orientation in `out_pose` — it writes the identity default up
    // front, which is exactly the path that used to emit zeroes.
    #[test]
    fn head_pose_orientation_normalized_without_context() {
        let mut pose = AlvrOxrPose {
            position: [0.0; 3],
            orientation: [0.0, 0.0, 0.0, 0.0], // deliberately degenerate input
        };
        let ret = unsafe { alvr_oxr_get_head_pose(0, &mut pose) };
        assert!(matches!(ret, AlvrOxrResult::NotInitialised), "got {ret:?}");
        assert!(
            (quat_norm_sq(pose.orientation) - 1.0).abs() < 1e-6,
            "head pose orientation not normalized without context: {:?}",
            pose.orientation
        );
    }
}
