//! Generates `include/alvr_runtime_bridge.h` from the `extern "C"` surface
//! of `src/lib.rs` using cbindgen. The Monado-side ALVR driver consumes
//! that header.

use std::{env, path::PathBuf};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=ALVR_REGENERATE_BRIDGE_HEADER");

    // The bridge header is the contract between this crate and the Monado-side
    // ALVR driver. To avoid an empty/partial cbindgen run silently clobbering
    // a hand-maintained header (which happens during normal `cargo check`),
    // regeneration is opt-in: set ALVR_REGENERATE_BRIDGE_HEADER=1 to refresh
    // `include/alvr_runtime_bridge.h` from the Rust source.
    if env::var("ALVR_REGENERATE_BRIDGE_HEADER").ok().as_deref() != Some("1") {
        return;
    }

    let crate_path = PathBuf::from(&crate_dir);
    let out_header = crate_path.join("include").join("alvr_runtime_bridge.h");

    std::fs::create_dir_all(out_header.parent().unwrap()).ok();

    let cfg = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        pragma_once: true,
        include_guard: Some("ALVR_RUNTIME_BRIDGE_H".to_owned()),
        no_includes: false,
        sys_includes: vec!["stdint.h".to_owned(), "stddef.h".to_owned()],
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::Doxy,
        ..Default::default()
    };

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(cfg);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(&out_header);
        }
        Err(err) => {
            // Do not fail the build on header-generation issues during
            // scaffolding; just warn. The header in version control may be
            // regenerated by a maintainer separately.
            println!(
                "cargo:warning=cbindgen failed to generate alvr_runtime_bridge.h: {err}. \
                 Continuing build; the existing header (if any) will be used."
            );
        }
    }
}
