//! Build script for `alvr_server_openxr`.
//!
//! Two responsibilities:
//!   1. Compile the platform-specific encoder backend C++ that lives in
//!      `../server_openvr/cpp/encoder/`. Today only the Windows Vulkan-input
//!      skeleton (`win32_vk/VkEncoderBackend.cpp`) is in scope; Slice 3.3
//!      adds the real implementation against NVENC's Vulkan-image-input
//!      API. The Linux side reuses `cpp/encoder/linux/EncodePipeline*` via
//!      Sub-slice 2.4, deferred.
//!   2. (Opt-in) Regenerate `include/alvr_runtime_bridge.h` from the
//!      `extern "C"` surface of `src/lib.rs` using cbindgen, gated by
//!      `ALVR_REGENERATE_BRIDGE_HEADER=1` so unrelated `cargo check` runs
//!      don't churn the header on disk.

use std::{env, path::PathBuf};

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let crate_path = PathBuf::from(&crate_dir);

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=ALVR_REGENERATE_BRIDGE_HEADER");
    println!("cargo:rerun-if-env-changed=VULKAN_SDK");

    let platform = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // --- (1) compile encoder backend C++ -----------------------------------
    //
    // The shared encoder C++ lives in the alvr_server_openvr tree under
    // cpp/encoder/. We reach into the sibling crate's path to compile the
    // pieces alvr_server_openxr needs (currently just the win32_vk skeleton
    // on Windows). Both crates share the same EncoderBackend.h interface.
    let cpp_root = crate_path.join("..").join("server_openvr").join("cpp");
    println!(
        "cargo:rerun-if-changed={}",
        cpp_root.join("encoder").to_string_lossy()
    );

    if platform == "windows" {
        let vk_dir = cpp_root.join("encoder").join("win32_vk");
        let vk_sources: Vec<PathBuf> = std::fs::read_dir(&vk_dir)
            .expect("cpp/encoder/win32_vk not found — alvr_server_openvr tree expected as sibling")
            .filter_map(|entry| entry.ok())
            .map(|entry| entry.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("cpp"))
            .collect();

        let mut build = cc::Build::new();
        build
            .cpp(true)
            .std("c++17")
            .files(vk_sources)
            .include(&cpp_root) // resolves `#include "encoder/EncoderBackend.h"`
            .define("NOMINMAX", None);

        // Vulkan SDK include path. Required even by the skeleton header
        // (which holds Vulkan types opaque today) so that Slice 3.3 can
        // start referencing VkImage / VkFormat without another build.rs
        // round-trip. The SDK is the standard LunarG installer; sets
        // VULKAN_SDK env var.
        if let Some(sdk) = env::var_os("VULKAN_SDK") {
            let sdk_path = PathBuf::from(sdk);
            build.include(sdk_path.join("Include"));
            println!(
                "cargo:rustc-link-search=native={}",
                sdk_path.join("Lib").to_string_lossy()
            );
            // Don't link vulkan-1 yet — the skeleton calls no Vulkan
            // symbols. Slice 3.3 will add `println!("cargo:rustc-link-lib=vulkan-1")`
            // once the real impl uses VkImage / VkSemaphore.
        } else {
            println!(
                "cargo:warning=VULKAN_SDK not set; the encoder skeleton will compile but \
                 Slice 3.3's real Vulkan-input NVENC integration will need it. \
                 Install the LunarG Vulkan SDK and re-build."
            );
        }

        build.compile("alvr_server_openxr_encoder");
    }

    // --- (2) cbindgen bridge-header regeneration (opt-in) ------------------
    if env::var("ALVR_REGENERATE_BRIDGE_HEADER").ok().as_deref() != Some("1") {
        return;
    }

    let out_header = crate_path.join("include").join("alvr_runtime_bridge.h");

    std::fs::create_dir_all(out_header.parent().unwrap()).ok();

    let cfg = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        pragma_once: true,
        include_guard: Some("ALVR_RUNTIME_BRIDGE_H".to_owned()),
        header: Some(
            "/* ALVR is licensed under the MIT license. \
             https://github.com/alvr-org/ALVR/blob/master/LICENSE */"
                .to_owned(),
        ),
        autogen_warning: Some(
            "/* Warning, this file is autogenerated by cbindgen. \
             Regenerate via `ALVR_REGENERATE_BRIDGE_HEADER=1 cargo build -p alvr_server_openxr`. */"
                .to_owned(),
        ),
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::Doxy,
        // Match the convention used by alvr_server_core/cbindgen.toml so that
        // C consumers get globally-unique enumerator names like
        // ALVR_OXR_SIDE_LEFT instead of a bare Left that would collide with
        // any other enum variant.
        enumeration: cbindgen::EnumConfig {
            rename_variants: cbindgen::RenameRule::QualifiedScreamingSnakeCase,
            ..Default::default()
        },
        ..Default::default()
    };

    let builder = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(cfg);

    match builder.generate() {
        Ok(bindings) => {
            bindings.write_to_file(&out_header);
        }
        Err(err) => {
            // Do not fail the build on header-generation issues during
            // scaffolding; just warn. The header in version control may be
            // regenerated by a maintainer separately.
            println!(
                "cargo:warning=cbindgen failed to generate alvr_runtime_bridge.h: {err}. \
                 Continuing build; the existing header (if any) will be used."
            );
        }
    }
}
